addons/crm/i18n/pt.po, addons/hr_timesheet/i18n/pt_BR.po, addons/sales_team/i18n/pt_BR.po
Description of the issue/feature this PR addresses:
New Translations
Current behavior before PR:
Desired behavior after PR is merged:
--
=> 10.0 develop

addons/hr_contract/i18n/pt_BR.po
Description of the issue/feature this PR addresses:
Current behavior before PR:
Desired behavior after PR is merged:
--
=> [FIX]Tradução do módulo hr_contract

addons/account/i18n/account.pot, addons/account/models/account_bank_statement.py, addons/account/report/account_invoice_report.py, addons/crm/i18n/pt.po, addons/hr_timesheet/i18n/pt_BR.po, addons/l10n_fr_hr_payroll/report/report_l10n_fr_fiche_paye.xml, addons/mrp/models/mrp_production.py, addons/pad/i18n/en.po, addons/product/models/res_company.py, addons/purchase/models/purchase.py, addons/sale/security/sale_security.xml, addons/sale_mrp/sale_mrp.py, addons/sale_timesheet/models/procurement.py, addons/sales_team/i18n/pt_BR.po, addons/stock/models/res_company.py, addons/stock/models/stock_move.py, addons/stock/views/stock_picking_views.xml, addons/stock_account/models/stock.py, addons/web/static/src/js/action_manager.js, addons/web_kanban/static/src/js/kanban_column.js, addons/website/static/src/js/website.snippets.animation.js, addons/website/static/src/js/website.snippets.editor.js, addons/website/static/src/less/website.snippets.less, addons/website_form/controllers/main.py, addons/website_sale/views/templates.xml, doc/cla/individual/josefkaser.md, doc/cla/individual/zeroheure.md, doc/howtos/backend.rst, odoo/models.py
Description of the issue/feature this PR addresses:
Current behavior before PR:
Desired behavior after PR is merged:
--
=> Traduções que haviam sido removidas

addons/account/views/account_invoice_view.xml
Adicionado tags *name* nas pages de Fatura de Fornecedor
close https://github.com/multidadosti-erp/erp-project/issues/115
=> Ajuste na fatura para NFSe

odoo/addons/base/res/res_users_view.xml
close https://github.com/multidadosti-erp/erp-project/issues/153
=> Criar botão para alterar senha na tela de preferências de usuário

addons/account/i18n/pt_BR.po
https://github.com/multidadosti-erp/erp-project/issues/197
=> Acertos de Relatórios

addons/base_setup/i18n/pt_BR.po, addons/hr/i18n/pt_BR.po, addons/hr_attendance/i18n/pt_BR.po, addons/hr_timesheet/i18n/pt_BR.po, addons/mail/i18n/pt_BR.po, addons/phone_validation/i18n/pt_BR.po, addons/product/i18n/pt_BR.po, addons/purchase/i18n/pt_BR.po, addons/resource/i18n/pt_BR.po, addons/sale_stock/i18n/pt_BR.po, addons/sale_timesheet/i18n/pt_BR.po, addons/stock_account/i18n/pt_BR.po, addons/web/i18n/pt_BR.po, addons/website/i18n/pt_BR.po, odoo/addons/base/i18n/pt_BR.po
**Adiciona traduções**
PR's relacionados
- [multidadosti-erp/others-addons#66](https://github.com/multidadosti-erp/others-addons/pull/66)
- [multidadosti-erp/odoo-brasil-addons#218](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/218)
- [multidadosti-erp/multidadosti-private-addons#235](https://github.com/multidadosti-erp/multidadosti-private-addons/pull/235)
- https://github.com/multidadosti-erp/multidadosti-addons/pull/441
[T2103](https://multi.multidadosti.com.br/web#id=2512&view_type=form&model=project.task&action=323&active_id=61)
=> T2103 - Tradução e padronização de ambiente

addons/account/i18n/pt_BR.po
Adiciona e corrige traduções da tela fornecedores
[T2317](https://multi.multidadosti.com.br/web#id=2726&view_type=form&model=project.task&action=323&active_id=61)
=> T2317 - Alteração de Nomenclatura

addons/mail/i18n/pt_BR.po
[FIX] Traduz texto da tela "Convidar Seguidor"
- Traduz também o módulo "mail" do core
[T2558](https://multi.multidadosti.com.br/web#id=2967&view_type=form&model=project.task&action=323&active_id=61)
=> T2558 - Traduzir texto

addons/account/i18n/pt_BR.po
[FIX] Corrige traduções erradas
[T2626](https://multi.multidadosti.com.br/web#id=3035&view_type=form&model=project.task&action=323&active_id=61)
Depende do [PR](https://github.com/multidadosti-erp/multidadosti-financial-addons/pull/202)
=> T2626 - Modificação de Label - "Reconciliação" - p/"Conciliação"

addons/hr_holidays/tests/test_automatic_leave_dates.py
[NEW] Adiciona Timezone nos testes do hr_holidays no core.
[T3635](https://multi.multidadosti.com.br/web#id=4044&view_type=form&model=project.task&action=323&active_id=61)
=> T3635-l10n_br / br_hr_payroll

addons/sale/tests/test_sale_transaction.py
[DEL] Remove teste test_sale_invoicing_from_transaction do core
[T3728](https://multi.multidadosti.com.br/web#id=4137&view_type=form&model=project.task&action=323&active_id=61)
=> T3728-multidadosti / public-addons / crm_lead_attachment

addons/base_import/i18n/pt_BR.po
[MIG] Tradução modulo do core 'base_import' odoo 12
[T3874](https://multi.multidadosti.com.br/web?#id=4283&view_type=form&model=project.task&action=323&active_id=61)
=> T3874-Traduzir modulo BASE_IMPORT Odoo 12

odoo/addons/base/i18n/pt_BR.po
[MIG] Tradução do 'base'
[T3866](https://multi.multidadosti.com.br/web#id=4275&view_type=form&model=project.task&action=323&active_id=61)
=> T3866-Traduzir module "BASE" Odoo 12 Core

addons/hr_timesheet/i18n/pt_BR.po
[IMP] Atualiza tradução de 'hr_timesheet' para 12.0
[T3967](https://multi.multidadosti.com.br/web#id=4376&view_type=form&model=project.task&action=323&active_id=61)
=> T3967-Tradução de Mensagem - compor projeto

addons/website/views/website_templates.xml
[IMP] Comenta template login_layout para impedir que o mesmo
[T3997](https://multi.multidadosti.com.br/web#id=4406&view_type=form&model=project.task&action=323&active_id=61)
=> T3997-Adaptar o Theme MUK para WEB SITE Odoo 12

addons/portal/i18n/pt_BR.po
[IMP] Traduz módulo "portal" do core
[T3841](https://multi.multidadosti.com.br/web#id=4250&view_type=form&model=project.task&action=323&active_id=61)
=> T3841-Traduzir o Model PORTAL Odoo 12

addons/contacts/i18n/pt_BR.po, addons/contacts/models/res_users.py, addons/mail/i18n/pt_BR.po, addons/mail/static/src/xml/systray.xml
[IMP] Corrige tradução do módulo mail
[IMP] Corrige tradução não carregada do módulo "contacts"
A tradução não ocorria mesmo com tudo feito corretamente,
então foi decidido que deveria ser feita a tradução no próprio código
[T3964](https://multi.multidadosti.com.br/web#id=4373&view_type=form&model=project.task&action=323&active_id=61)
=> T3964-Acertar Tradução da Lista das Atividades Odoo 12

addons/sale/i18n/pt_BR.po, addons/sale_management/i18n/pt_BR.po
[IMP] Corrige traduções no módulo sale
[T4013](https://multi.multidadosti.com.br/web#id=4422&view_type=form&model=project.task&action=323&active_id=61)
Depende dos PRs:
https://github.com/multidadosti-erp/odoo-brasil-addons/pull/341
https://github.com/multidadosti-erp/multidadosti-private-addons/pull/468
=> T4013-Mudar Tradução do modulo 'Sale' Odoo 12

addons/sale/i18n/pt_BR.po, addons/web/i18n/pt_BR.po
- Acerta tradução pt_br modulo 'sale' Odoo 12
- Acerta tradução pt_br modulo 'web' para Odoo 12
[T4059](https://multi.multidadosti.com.br/web?#id=4468&view_type=form&model=project.task&action=323&active_id=61)
=> T4059-Acertar Tradução do Dialogo 'Save & Close" e Cotação para Orçamento Odoo 12

addons/survey/i18n/pt_BR.po, odoo/http.py
- Remove dados do Odoo no modulo 'oh_appraisal' - 'survey'
- Atualizada a tradução pt_br no modulo 'survey'
[T4085](https://multi.multidadosti.com.br/web?#id=4494&view_type=form&model=project.task&action=323&active_id=61)
PR Relacionado: [133](https://github.com/multidadosti-erp/others-addons/pull/133)
=> T4085-Acertos no modulo 'SURVEY' Odoo 12

odoo/addons/base/i18n/pt_BR.po
[FIX] Acerta tradução PT_BR modulo 'Base' Odoo 12
[T4101](https://multi.multidadosti.com.br/web?#id=4510&view_type=form&model=project.task&action=323&active_id=61)
PRs Relacionados: [557](https://github.com/multidadosti-erp/multidadosti-addons/pull/557) e [49](https://github.com/multidadosti-erp/multidadosti-packages-addons/pull/49)
=> T4101-Remover o Modulo 'base_partner_activity_branch' e Acertar o Cadastro de Parceiros - Odoo 12

addons/crm/tests/__init__.py, addons/im_support/tests/__init__.py, addons/point_of_sale/tests/__init__.py, addons/portal/tests/__init__.py, addons/project/tests/__init__.py, addons/sale_management/tests/__init__.py, addons/survey/tests/__init__.py, addons/web/tests/__init__.py, addons/web_editor/tests/__init__.py, addons/website/tests/__init__.py, odoo/addons/test_new_api/tests/__init__.py
* [FIX] Comenta códigos de ui incompatíveis com o novo tema
[T4064](https://multi.multidadosti.com.br/web#id=4473&view_type=form&model=project.task&action=323&active_id=61)
=> T4064-Migração runbot para 12.0

addons/mail/i18n/pt_BR.po
[FIX] Acerta tradução pt_br modulo 'mail' Odoo 12
[T4102](https://multi.multidadosti.com.br/web?#id=4511&view_type=form&model=project.task&action=323&active_id=61)
PR Relacionado: [134](https://github.com/multidadosti-erp/others-addons/pull/134)
=> T4102-Adicionar Modulo para Visualização das Atividades no Calendário

addons/project/i18n/pt_BR.po
[IMP] Acerta tradução pt_br modulo 'project' Odoo 12
[T4196](https://multi.multidadosti.com.br/web?#id=4605&view_type=form&model=project.task&action=323&active_id=61)
=> [T4196] Acertar Textos da Tarefa campo KANBAN_STATE

addons/account_bank_statement_import/i18n/pt_BR.po
[FIX] Atualiza tradução pt_br modulo 'account_bank_statement_import'
[T4128](https://multi.multidadosti.com.br/web?#id=4537&view_type=form&model=project.task&action=323&active_id=61)
PR Relacionado: [139](https://github.com/multidadosti-erp/others-addons/pull/139)
=> T4128-Corrigir a Falta do Modulo de Conciliação Bancária

addons/uom/i18n/pt_BR.po
[IMP] Atualiza tradução "pt_br" modulo "UOM" Odoo 12
[T4254](https://multi.multidadosti.com.br/web?#id=4663&view_type=form&model=project.task&action=323&active_id=61)
=> T4254-Traduzir o modulo 'UOM' pt_br Odoo 12

addons/stock/i18n/pt_BR.po
[IMP] Atualiza tradução pt_br modulo "stock" Odoo 12
[T4261](https://multi.multidadosti.com.br/web?#id=4670&view_type=form&model=project.task&action=323&active_id=61)
=> T4261-Acertar Tradução "Produtos" Odoo 12

addons/portal/views/portal_templates.xml, addons/sale_quotation_builder/views/sale_portal_templates.xml, addons/website/views/website_templates.xml, addons/website_event/views/event_templates.xml, addons/website_sale/views/templates.xml
[IMP] Remove dos modulos Web do Core a Propagando do Odoo
[T4361](https://multi.multidadosti.com.br/web?#id=4770&view_type=form&model=project.task&action=323&active_id=61)
=> T4361-Remover do CORE do Odoo Propagandas do Odoo

addons/sale_timesheet/i18n/pt_BR.po
[FIX] Corrige tradução.
[T4324](https://multi.multidadosti.com.br/web#id=4733&view_type=form&model=project.task&action=323&active_id=61)
Depende do PR:
https://github.com/multidadosti-erp/multidadosti-addons/pull/572
=> T4324-Acertar Imagem do OverView do Projeto e Acertar Tradução

addons/note/i18n/pt_BR.po
[IMP] Atualiza tradução pt_br modulo 'note'
[T4322](https://multi.multidadosti.com.br/web?#id=4731&view_type=form&model=project.task&action=323&active_id=61)
PR Relacionado: [144](https://github.com/multidadosti-erp/others-addons/pull/144)
=> T4322-Liberar o menu Configuração no Modulo de Anotações e Acertar Tradução

addons/stock/i18n/pt_BR.po
[IMP] Atualiza tradução pt_br modulo 'stock'
[T4528](https://multi.multidadosti.com.br/web?#id=4937&view_type=form&model=project.task&action=323&active_id=61)
--
=> T4528-Trocar Texto de Inventário para Estoque

addons/account/i18n/pt_BR.po, addons/im_livechat/i18n/pt_BR.po, addons/im_livechat_mail_bot/i18n/pt_BR.po, addons/im_support/i18n/pt_BR.po
[IMP] Atualiza tradução 'pt_br' modulo 'account'
[IMP] Atualiza tradução 'pt_br' modulo 'im_livechat_mail_bot'
[IMP] Atualiza tradução 'pt_br' modulo 'im_livechat'
[IMP] Atualiza tradução 'pt_br' modulo 'im_support'
[T4552](https://multi.multidadosti.com.br/web?&debug=#id=4961&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T4552 - Acertar Tradução pt_br Básica do Core

odoo/addons/base/security/base_security.xml
[FIX] Corrige domain_force - Multi-Company modulo 'base' do Core
[T4568](https://multi.multidadosti.com.br/web#id=4977&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T4568 - Revisão de orçamento - Erro de Permissão de Multi Empresa

addons/sale_timesheet/i18n/pt_BR.po
[IMP] Atualiza tradução pt_br modulo 'sale_timesheet'
[T4584](https://multi.multidadosti.com.br/web?debug#id=4993&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T4584 - Erro: Acertar Tradução Visão Geral do Projeto no Core

addons/crm/i18n/crm.pot, addons/crm/i18n/pt_BR.po, addons/crm/models/crm_team.py
[IMP] Adiciona função de tradução no modulo 'CRM' no Core
[IMP] Acerta tradução pt_br do modulo 'CRM' …
- Arquivo POT
- Arquivo PO
[T4594](https://multi.multidadosti.com.br/web#id=5003&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T4608 - Acertar Tradução Oportunidades

addons/crm/i18n/pt_BR.po
[IMP] Atualiza tradução pt_br modulo 'CRM'
[T4617](https://multi.multidadosti.com.br/web?#id=5026&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
PR Relacionado: [454](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/454)
=> T4617 - Acertar tradução da Prioridade das Oportunidades

addons/crm/data/crm_stage_data.xml, addons/delivery/data/delivery_data.xml, addons/event_sale/data/event_sale_data.xml, addons/point_of_sale/data/point_of_sale_data.xml, addons/pos_restaurant/data/pos_restaurant_demo.xml, addons/product/data/product_data.xml, addons/product/data/product_demo.xml, addons/project/data/project_demo.xml, addons/sale_timesheet/data/sale_service_demo.xml
* [FIX] Adiciona 'forcecreate=False' nos registros default de categoria de produtos, estagios do projeto e estagios da oportunidade. 
PR relacionado: https://github.com/multidadosti-erp/project/pull/3
[T4630](https://multi.multidadosti.com.br/web#id=5039&action=323&active_id=61&model=project.task&view_type=form&menu_id=)
=> T4630 - O sistema sobrescreve os estágios padrão ao atualizar

addons/crm/i18n/pt_BR.po, addons/website_crm_partner_assign/i18n/pt_BR.po, odoo/addons/base/i18n/pt_BR.po
[IMP] Atualiza tradução pt_br nos Modulos do Core
- CRM
- Website CRM Partner Assign
- Base
[T4644](https://multi.multidadosti.com.br/web?#id=5053&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T4644 - Acertar Tradução: Contacto para Contato no Odoo

addons/crm/security/crm_security.xml
[IMP] Adiciona MultiCompany nas Regras modulo 'crm'
[T4688](https://multi.multidadosti.com.br/web?#id=5097&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T4688 - Adicionar Multi Company - Oportunidades

addons/digest/i18n/pt_BR.po, addons/sale_management/i18n/pt_BR.po
[IMP] Atualiza tradução pt_br modulo 'digest'
[IMP] Atualiza tradução pt_br modulo 'sale_management'
[T4842](https://multi.multidadosti.com.br/web?#id=5251&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T4842 - Traduzir o Modulo Digest do Odoo

addons/stock/data/stock_data.xml, addons/stock/models/stock_warehouse.py, addons/stock/static/src/js/stock_traceability_report_backend.js, addons/stock/tests/test_move2.py
* [FIX] Acerta tradução do relatório de rastreabilidade
Dados da tarefa: [T4840](https://multi.multidadosti.com.br/web#id=5249&action=323&active_id=61&model=project.task&view_type=form&menu_id=)
=> T4840 - Acertar Tradução do Relatório de Rastreabilidade do Estoque

addons/point_of_sale/data/point_of_sale_data.xml
[IMP] Comenta data/sale modulo 'point_of_sale'
- Comentado Data para Evitar Conflito de Registros com bases já
populadas.
Dados da tarefa: [T4883](https://multi.multidadosti.com.br/web?debug#id=5292&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T4883 - Erro: Ao instalar o modulo BR_POS no ambiente MultiPhono (Nossa demo)

addons/stock/i18n/pt_BR.po, addons/stock/wizard/stock_backorder_confirmation_views.xml
[IMP] Atualiza tradução pt_br do modulo 'stock' 
- Ajuste tradução de acordo com a necessidade e entendimento do processo
de recebimento e separação dos produtos no estoque.
[IMP] Troca CSS para melhor visualização da msg modulo 'stock' 
- Troca class CSS para dar um destaque na mensagem que é importante
para o usuário fazer a correta seleção.
Dados da tarefa: [T5072](https://multi.multidadosti.com.br/web?#id=5481&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T5072 - Acertar as Mensagens do Recebimento de Mercadoria

addons/account/views/account_payment_view.xml
- [IMP] Comenta action que não serve para nada atualmente
- [T4974](https://multi.multidadosti.com.br/web?#id=5383&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [PR relacionado](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/553): l10n_br
=> T4974 - REGISTRAR PAGAMENTOS

addons/purchase/views/purchase_views.xml
* [IMP] Adiciona id para identificação de botão com xpath no Pedido de Compra
Dados da tarefa: [T5070](https://multi.multidadosti.com.br/web#id=5479&action=323&active_id=61&model=project.task&view_type=form&menu_id=)
=> T5070 - Adicionar os Impostos (IPI e ICMS) e Parcelas no Modulo de Compras

addons/auth_signup/data/auth_signup_data.xml, addons/auth_signup/i18n/pt_BR.po
- [IMP] Atualizando templates de email padrão do Odoo
- [T4585](https://multi.multidadosti.com.br/web?#id=4994&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T4585 - Alteração no email de boas vindas do Sistema

addons/web/static/src/scss/form_view.scss
[IMP] Adiciona tag CSS no form_view
- Acerta formatação do Status Bar quando estoura as Colunas
Dados da tarefa: [T5348](https://multi.multidadosti.com.br/web?debug#id=5757&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
**Antes:**
**Depos:**
=> T5348 - Ajustar CSS qdo estoura StatusBar e Button

addons/crm/i18n/pt_BR.po
[IMP] Ajusta nome de filtro
- De Ultimas Atividades para Atividades Atrasadas
Dados da tarefa: [T5352](https://multi.multidadosti.com.br/web?#id=5761&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T5352 - Criação de Filtro para Atividades Atrasadas

addons/web/static/src/js/views/calendar/calendar_renderer.js, addons/web/static/src/scss/primary_variables.scss, addons/web/static/src/scss/web_calendar.scss
[IMP] Adiciona mais cores ao Web Calendar modulo 'web'
- Aumenta de 24 para 36 as cores
- Altera o CSS do Calendario
Dados da tarefa: [T5482](https://multi.multidadosti.com.br/web?#id=5891&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T5482 - Alteração das cores das Atividades

addons/crm/views/crm_lead_views.xml
- [IMP] Adicionando atributo 'name' para grupo para facilitar XPATH
- [T5512](https://multi.multidadosti.com.br/web?#id=5921&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [l10n_br](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/649)
=> T5512 - Bloquear a Inclusão e Edição na Oportunidade de: Campanhas, Mídia e Fonte

addons/website/models/website.py, addons/website/tests/test_menu.py
- [FIX] Corrigindo criação e atualização dos menus do website
- [T5532](https://multi.multidadosti.com.br/web?#id=5941&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [web-addons](https://github.com/multidadosti-erp/multidadosti-web-addons/pull/87)
=> T5532 - Ajustar Menu do Portal

addons/point_of_sale/i18n/pt_BR.po
- [IMP] Troca Tradução de 'Pagamento' por 'Finalizar'
- [T5573](https://multi.multidadosti.com.br/web?#id=5982&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [l10n_br](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/664)
=> T5573 - Criar opção de selecionar mais de uma variante do produto no POS da Kanxa

addons/point_of_sale/i18n/pt_BR.po, addons/point_of_sale/static/src/js/models.js
- [IMP] Adiciona função JS para adicionar domains a modelos já carregados
- [IMP] Adicionando Traduções que faltavam do POS.
- [T5601](https://multi.multidadosti.com.br/web?#id=6010&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [l10n_br](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/680)
=> T5601 - Filtro de clientes atraves do Vendedor não funcionou no ambiente da Kanxa

addons/account/i18n/pt_BR.po, addons/crm/i18n/pt_BR.po
- [FIX] Adicionando tag para funcionar a tradução de 'Undefined'
- [T5604](https://multi.multidadosti.com.br/web?#id=6013&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [l10n_br](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/690)
=> T5604 - Adicionar no Painel de Clientes o Grupo de Vendedor e Acertar Tradução

odoo/models.py
- [IMP] Adiciona função de obter valores decimais em string monetária
- [T5645](https://multi.multidadosti.com.br/web?#id=6054&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [report-addons](https://github.com/multidadosti-erp/multidadosti-report-addons/pull/206)
=> T5645 - Impressão de Etiquetas de Produto com REFERENCIA INTERNA ao inves de CODIGO DE BARRAS

addons/product/models/product_template.py
- [IMP] Cria função para obter valores de criação das variantes com finalidade de facilitar herança
- [T5646](https://multi.multidadosti.com.br/web?#id=6055&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [l10n_br](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/695)
=> T5646 - Na busca dos produtos no POS o sistema nao encontra o item pelo codigo

addons/account/views/product_view.xml
- [IMP] Troca o groups de financeiro da página do notebook para os subgrupos permitindo que o usuário comum visualize alguns itens da página
- [T5694](https://multi.multidadosti.com.br/web?#id=6103&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T5694 - Cadastro de produto

addons/stock/i18n/pt_BR.po
[FIX] Atualiza tradução pt_br do modulo 'stock'
- Atualiza a tradução para o correto compreendimento da Flag do Odoo
Dados da tarefa: [T5737](https://multi.multidadosti.com.br/web?#id=6146&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T5737 - O sistema esta sugerindo Números de Série Automaticamente

addons/point_of_sale/i18n/point_of_sale.pot, addons/point_of_sale/i18n/pt_BR.po, addons/stock/i18n/pt_BR.po
- [FIX] Correções na tradução do ponto de venda
- [T5603](https://multi.multidadosti.com.br/web?#id=6012&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T5603 - Acertar Tradução do modulo BR_POS

addons/stock/views/stock_location_views.xml
- [FIX] Adiciona tag sheet para ajustar a tela com o padrão do sistema
- [T5778](https://multi.multidadosti.com.br/web?#id=6187&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T5778 - Arrumar a tela do estoque com o padrão do sistema

odoo/addons/base/rng/tree_view.rng
[IMP] Adiciona tags tree_view.rng modulo 'base'
- Adiciona 2 novas tags: tree_field_list e tree_edit_list
Obs.: Através dessas novas tags é possível criar atributos
para Tree
Dados da tarefa: [T5836](https://multi.multidadosti.com.br/web?debug#id=6245&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
PR(s) relacionado(s) (se houver): [754](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/754)
=> T5836 - Adicionar nas Configurações dos Campos da Tree o Nome para não misturar com outras visões

addons/account/models/account_move.py
[FIX] Adiciona verificação de consistencia de IDs modulo 'account'
- Adiciona verificação de existencia de move para criação do move_line
Evitando erro de consistência de dados de 'filho sem pai'.
Dados da tarefa: [T5797](https://multi.multidados.tech/web?debug#id=6206&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
PR(s) relacionado(s) (se houver): [770](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/770)
=> T5797 - Erro ao cancelar fatura com E-Doc Cancelado

addons/account/models/account_payment.py
[IMP] Comenta Trava modulo 'account'
- Trava comentada para ser utilizada dependendo da situação na
localização.
Dados da tarefa: [T5843](https://multi.multidados.tech/web?debug#id=6252&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
PR(s) relacionado(s) (se houver): [768](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/768)
=> T5843 - Adicionar Opção de Adiantamento de Valores nos Pedidos

addons/web/static/src/js/views/calendar/calendar_model.js
[IMP] Adiciona Configuração Calendario via Context modulo 'web'
- Adiciona Context para:
'snapMinutes', 'slotDuration' , 'minTime' e 'maxTime'
Dados da tarefa: [T5898](https://multi.multidados.tech/web#id=6307&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
[599](https://github.com/multidadosti-erp/multidadosti-addons/pull/599)
[772](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/772)
=> T5898 - Adicionar Configuração Calendário

addons/product/views/product_views.xml
- [IMP] Adicionando atributo 'name' em tags nas views
- [T5820](https://multi.multidados.tech/web?#id=6229&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [l10n_br](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/775)
=> T5820 - Problema em entrada de xml

addons/mail/models/mail_activity.py
- [IMP] Altera trecho de código por função para facilitar herança
- [T5887](https://multi.multidados.tech/web?#id=6296&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [l10n_br](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/776)
=> T5887 - Ao concluir um atividade atrasada e marcar uma nova o marcador da atividade atrasa ainda aparece

addons/google_calendar/models/google_calendar.py
[FIX] Corrige Sincronização com Google Calendar modulo 'google_calendar'
- Adiciona Verificação de Registro para Evitar Duplicação
- Adiciona Verificação de Retorno do Google para Evitar erro de
Exception when updating recurrent event exclusions on google: 'str' object has no attribute 'get'
Dados da tarefa: [T5916](https://multi.multidados.tech/web#id=6325&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T5916 - Erro: Na sincronização com o Google Calendar

addons/sale/report/sale_report_templates.xml, addons/web/views/report_templates.xml, odoo/addons/base/views/ir_qweb_widget_templates.xml
- [IMP] Adicionando Tag 'name' para facilitar XPATH
- [T5884](https://multi.multidados.tech/web?#id=6293&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [report-addons](https://github.com/multidadosti-erp/multidadosti-report-addons/pull/220)
=> T5884 - Alterações na impressão do pedido e inclusão de modelo POS

addons/crm/tests/test_crm_activity.py
[IMP] Comentado teste modulo 'crm' ref a Atividades
- Comentado parte do Teste onde Verifica se a Atividade foi
excluida.
Dados da tarefa: [T5954](https://multi.multidados.tech/web?debug#id=6363&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
[798](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/798)
[688](https://github.com/multidadosti-erp/multidadosti-private-addons/pull/688)
[1](https://github.com/multidadosti-erp/social/pull/1)
=> T5954 - Adicionar Histórico das Atividades

odoo/addons/test_impex/tests/test_load.py, odoo/models.py
[FIX] Aumenta limite de Erros na Importação modulo 'addons'
- Aumentado o limite de 10 para 1000 para poder ignorar erros
e importar registros corretos.
Dados da tarefa: [T6101](https://multi.multidados.tech/web?#id=6510&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
PR(s) relacionado(s) (se houver): [840](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/840)
=> T6101 - Problema na validação do CNPJ na importação de fornecedores

addons/web/static/lib/tempusdominus/tempusdominus.js
- [FIX] Trata erro da validação de data no datepicker JS
- [T6095](https://multi.multidados.tech/web#id=6504&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T6095 - Erro: Ao clicar em Criar SubTarefa de uma SubTarefa ja Criada da erro no JS

addons/project/i18n/pt_BR.po
- [FIX] Corrige tradução do modelo de email de feedback tarefas
- [T6017](https://multi.multidados.tech/web#id=6426&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T6017 - Traduzir Email ref pesquisa satisfação das tarefas

addons/mail/models/mail_activity.py
- [FIX] Opção de herdar cláusula where do 'mail.activity'
- Para facilitar a herança do método do core, foi substituído um pequeno trecho de código por uma função, para poder modificar a query realizada nos módulos que necessitarem, como por exemplo o 'mail_activity_done' que adiciona 2 condições na query.
- [T6229](https://multi.multidados.tech/web#id=6638&action=1139&active_id=12&model=project.task&view_type=form&menu_id=223)
- [private-addons](https://github.com/multidadosti-erp/multidadosti-private-addons/pull/717)
- [oca/social](https://github.com/multidadosti-erp/social/pull/6)
=> T6229 - Corrigir progressbar das atividades que aparecem como atrasadas

addons/purchase/views/purchase_views.xml
- [IMP] Adiciona atributo name na página para facilitar XPATH
- [T6242](https://multi.multidados.tech/web#id=6651&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [l10n_br](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/895)
=> T6242 - Ajustar Tela de Compras

addons/project/i18n/pt_BR.po
- [FIX] Ajuste na tradução do campo 'privacy_visibility' do Projeto
- [T6218](https://multi.multidados.tech/web#id=6627&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [public-addons](https://github.com/multidadosti-erp/multidadosti-addons/pull/605)
=> T6218 - Acesso por equipe em projetos

addons/crm/views/res_config_settings_views.xml
* [IMP] Adiciona tag para uso de xpath
Dados da tarefa: [T6486](https://multi.multidados.tech/web#action=323&active_id=61&model=project.task&view_type=kanban&menu_id=)
=> T6486 - Erro ao visualizar configurações

addons/hr_expense/views/hr_expense_views.xml
- [IMP] Adiciona tag name para uso de xpath
Dados da tarefa: [T6458](https://multi.multidados.tech/web#id=6867&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [l10n_br](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/975)
- [packages-addons](https://github.com/multidadosti-erp/multidadosti-packages-addons/pull/72) 
- [private-addons](https://github.com/multidadosti-erp/multidadosti-private-addons/pull/739)
- [web-addons](https://github.com/multidadosti-erp/multidadosti-web-addons/pull/142)
- [public-addons](https://github.com/multidadosti-erp/multidadosti-addons/pull/608)
=> T6458 - Adicionar aos Contratos de Serviço: Eventos de Horas e Despesas

addons/point_of_sale/models/pos_order.py, addons/point_of_sale/static/src/js/models.js
- [FIX] Corrige erro na hora de apresentar erro no POS
- Os parâmetros da função estavam sendo passados na ordem errada, fazendo com que os valores que deveriam ser acessados de um dos parâmteros fossem incorretos, já que o objeto correto seria o outro parâmetro.
- Aumenta timeout da função
- [IMP] Altera trecho de criar fatura pelo POS por uma função
- [T6554](https://multi.multidados.tech/web#id=6963&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [l10n_br](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/987)
=> T6554 - Alterações/Correções no modulo de POS

addons/point_of_sale/i18n/pt_BR.po
[FIX] Ajusta Tradução pt_br do modulo 'point_of_sale'
Dados da tarefa: [T6597](https://multi.multidados.tech/web?#id=7006&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
PR(s) relacionado(s) (se houver): [1001](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1001)
=> T6597 - Alterar origem dos valores de TIPO DE TITULO e OPERAÇÃO FINANCEIRA do POS

addons/web/static/src/js/fields/relational_fields.js
- [IMP] Options 'no_create' em forma de domain do campo Many2one.
- Antes não era possível utilizar um domain para determinar se o 'no_create' deveria ser aplicado para um campo many2one, era utilizado apenas True ou False.
- [T6584](https://multi.multidados.tech/web#id=6993&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [l10n_br](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1005)
=> T6584 - Sugestão/Criação Nº Série

addons/utm/models/utm.py, addons/utm/security/ir.model.access.csv
[FIX] Ajusta permissões modulo 'utm'
- Ajusta Permissão para Excluir Dados
- Ajusta Criação dos Campos
Dados da tarefa: [T6540](https://multi.multidados.tech/web#id=6949&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T6540 - Exclui cadastro de campanhas

odoo/models.py
[Cria metodo para obter o Label de um campo Selection 'models'](https://github.com/multidadosti-erp/odoo/commit/39dd5f09f3b9dcdde04d471fb37b96b66cb02cd0)
Dados da tarefa: [T6671](https://multi.multidados.tech/web#id=7080&action=1109&active_id=6880&model=project.task&view_type=form&menu_id=465)
PR(s) relacionado(s) (se houver): [758](https://github.com/multidadosti-erp/multidadosti-private-addons/pull/758)
=> T6671 - Criação de Novos Tipos de Parceiros

addons/delivery/views/delivery_view.xml, addons/stock/views/stock_quant_views.xml
- Separa em grupos campos do peso e tipo de pacotes
- [T6623](https://multi.multidados.tech/web#id=7032&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [l10n_br](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1048)
- [report-addons](https://github.com/multidadosti-erp/multidadosti-report-addons/pull/263)
=> T6623 - Criação de Modelo de Etiqueta de Separação de Itens

odoo/addons/base/models/ir_attachment.py
Adiciona Index=True 'ir.attachment' modulo 'base'
Dados da tarefa: [T6788](https://multi.multidados.tech/web?debug#id=7197&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T6788 - Criar indices na tabela 'ir_attachment'

addons/account/views/account_view.xml
Inverte posição campos 'account.group' XML modulo 'account'
Dados da tarefa: [T6785](https://multi.multidados.tech/web?debug#id=7194&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
PR(s) relacionado(s) (se houver): 
[1071](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1071)
[773](https://github.com/multidadosti-erp/multidadosti-private-addons/pull/773)
[269](https://github.com/multidadosti-erp/multidadosti-report-addons/pull/269)
[472](https://github.com/multidadosti-erp/multidadosti-financial-addons/pull/472)
=> T6785 - Criar Categoria Financeira (baseado nas categorias dos produtos)

addons/web/static/lib/jquery.ui/jquery-ui.js, addons/website/models/website.py
[Corrige problema ao Editar Menus WebSite modulo 'web'](https://github.com/multidadosti-erp/odoo/commit/5fca01963f9ad6b29979664993dc837fcb334a35) 
- Atualiza versão do jquery-ui.js para 1.13.2
- Adiciona IF para tratar dragDirection se foi definido
[Corrige gravação campo compute modulo 'website'](https://github.com/multidadosti-erp/odoo/commit/8b2e873ef17b6f39179c9c158846dc5e31a6d6e6) 
- Remove da gravação dos Menus o campo 'is_homepage'
Dados da tarefa: [T6821](https://multi.multidados.tech/web#id=7230&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T6821 - Erro JS na edição dos menus

addons/sale_timesheet/tests/test_sale_service.py
* Ajusta testes do timesheet para metodo unlink
Dados da tarefa: [T6843](https://multi.multidados.tech/web#id=7252&action=323&active_id=61&model=project.task&view_type=form&menu_id=)
=> T6843 - Corrige exclusao de timesheet

addons/sale/models/sale.py
* Remove onchange para que o mesmo seja tratado no br_sale
Dados da tarefa: [T6775](https://multi.multidados.tech/web#id=7184&action=323&active_id=61&model=project.task&view_type=form&menu_id=)
=> T6775 - Sistema não está recalculando o impostos ao alterar a posição fiscal do Orçamento/Fatura

odoo/models.py
Adiciona novo parametro de Contexto: Método Create e Write
- Adiciona parametro: force_uid_log para forçar o log no usuário enviado. Isso é utilizado quando força a gravação pelo SUDO e assim o log ficava pelo BOT e não pelo usuário correto.
Para uso:
self.sudo().with_context(force_uid_log=user_id).create()
self.sudo().with_context(force_uid_log=user_id).write()
Dados da tarefa: [T7020](https://multi.multidados.tech/web#id=7429&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
PR(s) relacionado(s) (se houver): [486](https://github.com/multidadosti-erp/multidadosti-financial-addons/pull/486)
=> T7020 - Erro ao processar no CNAB em Fila 

addons/account/models/account_invoice.py, addons/account/models/account_move.py, addons/account/models/account_payment.py
Adiciona SUDO() no acesso a Dados Matriz/Filial módulo 'account'
- Adiciona sudo para ter acesso aos lançamentos efetuados nas filiais com contas da Matriz.
- Adiciona em Gravações o force_uid_log para registrar corretamente o usuário do lançamento (devido ao uso do SUDO).
Dados da tarefa: [T7061 ](https://multi.multidados.tech/web?#id=7470&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
PR(s) relacionado(s) (se houver): [1145](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1145)
=> T7061 - Erro ao realizar baixar titulo

addons/account/i18n/account.pot, addons/account/i18n/pt_BR.po, addons/account/views/account_invoice_view.xml, addons/account/views/partner_view.xml, addons/web/static/src/js/widgets/ribbon.js, addons/web/static/src/scss/ribbon.scss, addons/web/static/src/xml/ribbon.xml, addons/web/views/webclient_templates.xml
[Adiciona widget 'web_ribbon' módulo 'web'](https://github.com/multidadosti-erp/odoo/commit/38593228e7fe47bc9f8e7f738e4ea30458678c52)
[Atualiza 'account.pot' para corrigir traduções módulo 'account'](https://github.com/multidadosti-erp/odoo/commit/2f32b8776f1ec63bfb6506405a24ad00d64f7ee9)
[Adiciona 'widget_ribbon' módulo 'account'](https://github.com/multidadosti-erp/odoo/commit/475fffb59ebb080836fbcc7247179d424f3414d4) 
- Adiciona widget nos Formulários:
- Fatura
- Posição Fiscal
Dados da tarefa: [T7091 ](https://multi.multidados.tech/web?#id=7500&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T7091 - Adicionar ribbon para a visão form

addons/purchase/views/purchase_views.xml, odoo/models.py
[Ajusta Form Puchase módulo 'purchase'](https://github.com/multidadosti-erp/odoo/commit/46175c694b622de21b61f5ad9793b1b95eee502c) 
- Ajusta XML/View para melhorar a herança do form e adicionar
novos campos.
[Adiciona Contexto ID 'dynamic_default'](https://github.com/multidadosti-erp/odoo/commit/bd466961e8d966cc687874f419ac30a87545c04d) 
- Adiciona ao contexto o ID para uso nos métodos.
Dados da tarefa: [T7114 ](https://multi.multidados.tech/web?#id=7523&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
[816](https://github.com/multidadosti-erp/multidadosti-private-addons/pull/816)
[1171](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1171)
=> T7114 - Verificação dos Estoques COMPRAS/VENDAS/POS

addons/crm/views/crm_lead_views.xml
Ajusta View Prospectos módulo 'crm'
- Remove tag 'group' desnecessário.
- Adiciona tag 'name' nos groups para facilitar herança.
Dados da tarefa: [T7147 ](https://multi.multidados.tech/web?#id=7556&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T7147 - Ajustar Tela de prospecto

addons/sale/tests/test_sale_order.py
* Desabilita teste para novas regras de visual. do admin
Teste estava obseleto com as novas regras de visualização do usuario admin criado pelo PR do link abaixo.
Dados da tarefa: [T7198](https://multi.multidados.tech/web#id=7607&action=323&active_id=61&model=project.task&view_type=form&menu_id=)
PR(s) relacionado(s) (se houver): PR: https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1193
=> T7198 - Ajustar visibilidade do usuario admin

addons/crm/views/crm_lead_views.xml
Adiciona 'web_ribbon' módulo 'crm'
Dados da tarefa: [T7235 ](https://multi.multidados.tech/web?debug=#id=7644&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
PR(s) relacionado(s) (se houver): [1197](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1197)
=> T7235 - Adiciona Botão para Identificar duplicações nas Oportunidades

addons/web/static/lib/py.js/lib/py.js
Ajusta JS para Eviar Erro Odoo módulo 'web'
- Trata variável se for array convertendo para string como padrão de filtro (domain).
Dados da tarefa: [T7376 ](https://multi.multidados.tech/web#id=7785&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T7376 - Erro JavaScript ao Tentar Adicionar Favorito na Pesquisa

addons/analytic/views/analytic_account_views.xml
- View form dos timesheets passa a ser a do hr_timesheet
- [T7413](https://multi.multidados.tech/web#id=7822&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [l10n_br](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1244)
- [channel-addons](https://github.com/multidadosti-erp/multichannels-addons/pull/54)
- [private-addons](https://github.com/multidadosti-erp/multidadosti-private-addons/pull/843)
=> T7413 - Ajustes Despesas e Extrato API Lawps

addons/account/models/account_payment.py
* Corrige chamada do calculo de imposto ao criar pagamentos
Ao criamos ordem de pagamento, o sistema chama o metodo 'default_get' do pagamento que ao consultar os campos da invoice, acaba por invocar o metodo 'calculate_price_and_taxes'. Isso fazia com que os impostos fosse recalculados, podendo causar erro de calculos em impostos ao gerarmos o pagamento. A solução foi buscar os campos especificos que já estavam calculados e que seria usados, evitando que o metodo de recalculo seja chamado.
Dados da tarefa: [T7589](https://multi.multidados.tech/web?#id=7998&action=323&active_id=61&model=project.task&view_type=form&menu_id=)
=> T7589 - Erro "Valor total e parcelas divergentes" ao confirmar faturas importadas via XML

addons/account/i18n/account.pot, addons/account/i18n/pt_BR.po, addons/account/models/account_journal_dashboard.py, addons/account/models/reconciliation_widget.py, addons/account/views/account_journal_dashboard_view.xml
Ajusta 'account_journal_dashboard_view' módulo 'account'
- Corrige bug ao clicar no botão "Conciliar"
- Adiciona Saldo do Extrato no Painel Financeiro
- Atualiza tratução pt_br e .pot
Dados da tarefa: [T7574 ](https://multi.multidados.tech/web?debug#id=7983&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
PR(s) relacionado(s) (se houver): [1262](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1262)
=> T7574 - Erro no campo Diferença dos Diarios Financeiros

addons/stock/views/stock_quant_views.xml
Ajusta action 'quantsact' módulo 'stock'
- Substitui Filter no Context por Domain, para não deixar o usuário remover o filtro e gerar errado o relatório de inventário.
Dados da tarefa: [T7663](https://multi.multidados.tech/web?debug#id=8072&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
PR(s) relacionado(s) (se houver): [13](https://github.com/multidadosti-erp/multi-company/pull/13)
=> T7663 - Relatório Itens de Estoque na empresa Osasco

addons/stock/views/stock_quant_views.xml
- Remove o agrupamento de produto, deixando somente o agrupamento de localização do estoque.
Ajusta Group XML 'quantsact'  módulo 'stock'
Dados da tarefa: [T7697](https://multi.multidados.tech/web?debug#id=8106&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
PR(s) relacionado(s) (se houver): [1280](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1280)
=> T7697 - Relatório de Inventário - Add coluna código do item

addons/account/models/account_invoice.py
* Adiciona tag para que '._set_taxes' mantenha valor do 'price_unit'
Metodo 'set_taxes' do core sobrescreve valor do campo 'price_unit', fazendo que o valor do campo seja perdido. Esse comportamento nao é recomendavel em casos onde o 'price_unit' foi alterado pelo usuario devido a unica negociação ou por outro motivo.
Dados da tarefa: [T7769](https://multi.multidados.tech/web?#id=8178&action=328&model=project.task&view_type=form&menu_id=223)
=> T7769 - O sistema altera o valor unitario do item apos recarregar a Posição Fiscal

addons/stock/i18n/pt_BR.po, addons/stock/i18n/stock.pot, addons/stock/models/product.py, addons/stock/views/stock_quant_views.xml
Adiciona novo Filtro Contexto nos Saldos dos Produtos módulo 'stock'
- Adiciona Filtro na Pesquisa
- Adiciona Filtro no Contexto da Action
Dados da tarefa: [T7759](https://multi.multidados.tech/web?#id=8168&action=1109&active_id=8988&model=project.task&view_type=form&menu_id=465)
=> T7759 - Saldo do Estoque Atual

odoo/addons/base/views/res_partner_views.xml
Adiciona 'name' Tags/XML 'group' módulo 'base'
Dados da tarefa: [T7728](https://multi.multidados.tech/web#id=8137&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
PR(s) relacionado(s) (se houver): [155](https://github.com/multidadosti-erp/multidadosti-web-addons/pull/155)
=> T7728 - Melhorias Gestão Tickets

addons/web/static/src/js/views/kanban/kanban_record.js
- Melhorias e fnucionalidades na view Kanban
- Adiciona os atributos 'now' e 'today' para obter a partir do widget
- Adiciona atributo 'moment' para campos date e datetime na view kanban
- [T7681](https://multi.multidados.tech/web#id=8090&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [oca/social](https://github.com/multidadosti-erp/social/pull/12)
- [l10n_br](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1289)
- [private-addons](https://github.com/multidadosti-erp/multidadosti-private-addons/pull/857)
=> T7681 - Criar novo Kanban para visualizar melhor as Atividades

addons/web/static/src/js/views/kanban/kanban_column.js, addons/web/static/src/js/views/kanban/kanban_renderer.js, addons/web/static/src/js/views/kanban/kanban_view.js
- Ajusta 'draggable' do kanban JS
- [T7802](https://multi.multidados.tech/web#id=8211&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [oca/social](https://github.com/multidadosti-erp/social/pull/13)
- [l10n_br](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1291)
=> T7802 - Ajustes nas Mudanças do Multiphono

addons/stock/wizard/stock_picking_return.py
- Altera função de retorno de estoque no core para facilitar herança
- No retorno de um stock.picking, utilizando o wizard stock.picking.return, era criado sempre um picking do tipo Retorno a partir do picking que está sendo devolvido. Essa criação foi transferida para uma função para facilitar a herança, como no br_stock, onde tentamos obter um picking compatível para a inclusão do move, sem a necessidade de criar um novo picking.
- [T7874](https://multi.multidados.tech/web?#id=8283&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [l10n_br](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1339)
- [private-addons](https://github.com/multidadosti-erp/multidadosti-private-addons/pull/876)
=> T7874 - Notas fiscais de retorno de locação a partir de contato de serviço

addons/crm/models/res_partner.py
- Corrige action que abre view de oportunidades (CRM/Parceiro)
- os valores da action são reaproveitados, mudando apenas o domain e as views.
- [T7997](https://multi.multidados.tech/web?#id=8406&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T7997 - Não aparece botão "Criar" ao acessar as oportunidades através do modulo parceiros

addons/account_bank_statement_import/__init__.py, addons/account_bank_statement_import/__manifest__.py
* Desabilita modulo 'account_bank_statement_import'
Modulo foi substituido por modulo da localização
Dados da tarefa: [T8013](https://multi.multidados.tech/web#id=8422&action=323&active_id=61&model=project.task&view_type=form&menu_id=)
=> T8013 - Ajuste no modulo de importação OFX

addons/web/static/src/js/chrome/menu.js
- Corrige erro do menu de Apps não fechar após entrar no app
- [T8134](https://multi.multidados.tech/web?#id=8543&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [web-addons](https://github.com/multidadosti-erp/multidadosti-web-addons/pull/163)
=> T8134 - Gestão de Tickets - Módulo Atendimento (Continuação TI-09199)

addons/point_of_sale/static/src/js/screens.js
- Adiciona parâmetros, retornos e comportamentos em funções do POS
- Na função de filtrar os produtos pelo nome, na lista de produtos, foi adicionado na função que lida com os eventos de teclas clicadas, a opção de adicionar um timeOut para atualizar os produtos. Esse timeOut é implementado no módulo 'br_pos_base', na função 'perform_search' do 'ProductCategoriesWidget'.
- Foi adicionado um retorno na função 'peform_search' doa produtos que foram filtrados com a string da search-bar.
- [T8139](https://multi.multidados.tech/web?#id=8548&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [l10n_br](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1393)
=> T8139 - Inconsistência estoque - PDV São Miguel (URGENTE)

addons/google_calendar/views/res_users_views.xml, addons/product/i18n/product.pot, addons/product/i18n/pt_BR.po, addons/product/views/product_views.xml, addons/purchase_stock/models/purchase.py, addons/sale_stock/models/sale_order.py, odoo/addons/base/views/res_users_views.xml
[Ajusta XML/Form do Usuário módulo 'base'](https://github.com/multidadosti-erp/odoo/commit/6315c1d8d79ebee714f60f7affd49dc9f0902cdd) 
- Objetivo é melhorar a herança nos módulos dependentes.
[Adiciona Type do Produto no '_compute_qty_delivered' módulo 'sale_stock'](https://github.com/multidadosti-erp/odoo/commit/0c2e4342f9595970bc9b12e4cd8fa78e5098d19b) 
- Adicionado o Type para entrar somente nos tipos 'product' e 'consu'
[Ajusta Form dos Produtos módulo 'product'](https://github.com/multidadosti-erp/odoo/commit/ca4a697f57e76880d7774c088cc0524af6371352) 
[Melhora Hierarquia módulo 'purchase_stock'](https://github.com/multidadosti-erp/odoo/commit/ddc9c9e6f1db4062e898a0efb35fec2ca05dc02e) 
- Adiciona método para poder herdar e adicionar controle do type …
=> T8212 - Adicionar no módulo de vendas KIT de Produto/Serviço

addons/account/models/account_payment.py
Ajusta Validação das Invoices no Pagamento módulo 'account'
Dados da tarefa: [T8233](https://multi.multidados.tech/web#id=8642&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
PR(s) relacionado(s) (se houver): [1411](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1411)
=> T8233 - Erro ao Baixar o Título

addons/calendar/models/calendar.py
* Corrige arquivo .ics para eventos calendario
Arquivo não estava gerando eventos de calendario no outlook. Esta alteração adiciona novos parametros ao arquivo .ics e ajusta os parametros do mime-type do email para que o cliente do outlook reconheça os email com convites de reunião
Dados da tarefa: [T8294](https://multi.multidados.tech/web#id=8703&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T8294 - OutLook não adiciona automaticamente a Agenda

addons/hr_expense/i18n/pt_BR.po
- Atualiza tradução do módulo de Despesas
- [T8302](https://multi.multidados.tech/web?#id=8711&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [l10n_br](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1426)
- [private-addons](https://github.com/multidadosti-erp/multidadosti-private-addons/pull/909)
- [channel-addons](https://github.com/multidadosti-erp/multichannels-addons/pull/83)
=> T8302 - Ajustes na integração da Lawps (Despesas)

addons/purchase/views/purchase_views.xml
* Adiciona novas opcoes para campo empresa do Compras
Dados da tarefa: [T8330](https://multi.multidados.tech/web#id=8739&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T8330 - Usabilidade melhoria ticket TI-09712 - Solicitação de compra empresa do grupo

addons/account/models/account_invoice.py
Adiciona no Calculos das Parcelas os dias módulo 'account'
- Adiciona na Lista de Datas a informação dos dias aplicados.
Dados da tarefa: [T8353](https://multi.multidados.tech/web?debug#id=8762&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
[1434](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1434)
[914](https://github.com/multidadosti-erp/multidadosti-private-addons/pull/914)
=> T8353 - Adicionar Agendas aos Itens do Pedido do Tipo PROJETO CONTRATO DE ALOCAÇÃO

odoo/addons/base/models/res_partner.py
Ajusta Create Partner módulo 'base'
- Adiciona validação do 'message_follower_ids', pois no create não deve ter nada preenchido para evitar erro: duplicate key value violates unique constraint "mail_followers_mail_followers_res_partner_res_model_id_uniq"
Dados da tarefa: [T8377](https://multi.multidados.tech/web#id=8786&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
PR(s) relacionado(s) (se houver): [1441](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1441)
=> T8377 - Erro ao Importar Clientes

addons/web/static/lib/jquery.ui/jquery-ui.js, addons/web/static/lib/tempusdominus/tempusdominus.js, addons/web/static/src/js/views/calendar/calendar_renderer.js, addons/web/static/src/xml/web_calendar.xml, odoo/addons/base/models/res_partner.py
[Ajusta Create Partner módulo 'base'](https://github.com/multidadosti-erp/odoo/commit/cddfec0b5dbc4f40287150ede476023423078519) 
- Adiciona validação do 'message_follower_ids', pois no create
não deve ter nada preenchido para evitar erro:
duplicate key value violates unique constraint
"mail_followers_mail_followers_res_partner_res_model_id_uniq"
[Adiciona 'avatar_field' 'no_image' módulo 'web'](https://github.com/multidadosti-erp/odoo/commit/25d2afbafdbbf929c4bf0e1a986c5d02f9422a5d) 
- Adiciona a opção 'no_image' para não mostrar imagem nenhuma.
[Adiciona finction 'Origin_datepicker' módulo 'calendar'](https://github.com/multidadosti-erp/odoo/commit/768d2763947ea0882daaf3d8a045c8634ab2d8ef) 
- Adicionada function no JS para evitar conflitos com a Lib
'Bootstrap' utilizada no br_calendar. …
=> T8376 - Ajustes no Orçamento

addons/stock/models/stock_production_lot.py
Adiciona 'track_visibility' e Index nos campos do módulo 'stock'
Dados da tarefa: [T8337](https://multi.multidados.tech/web?debug#id=8746&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T8337 - Discussão TI-09944 - Edição N/S (Criação de Numero Lote/Numero de Serie)

addons/stock/models/stock_quant.py
Ajuste Parâmetro 'Location_id' método '_gather' módulo 'stock'
- Ajusta o parâmetro para ser opcional.
Dados da tarefa: [T8371](https://multi.multidados.tech/web?debug#id=8780&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
PR(s) relacionado(s) (se houver): [1453](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1453)
=> T8371 - Sistema está permitindo dar a entrada do mesmo numero de série em locais diferentes ao mesmo tempo

addons/base_import_module/models/base_import_module.py, addons/l10n_fr_fec/wizard/account_fr_fec.py, addons/l10n_it_edi/models/account_invoice.py, addons/l10n_it_edi/models/ir_mail_server.py, addons/pos_cache/models/pos_cache.py, addons/web/controllers/main.py, addons/website_form/controllers/main.py, odoo/addons/base/models/ir_actions_report.py, odoo/addons/base/models/ir_model.py, odoo/addons/base/models/ir_ui_menu.py, odoo/addons/base/models/qweb.py, odoo/addons/base/wizard/base_export_language.py, odoo/addons/base/wizard/base_import_language.py, odoo/addons/test_translation_import/tests/test_term_count.py, odoo/api.py, odoo/models.py, odoo/modules/registry.py, odoo/osv/expression.py, odoo/tests/common.py, odoo/tools/misc.py, odoo/tools/safe_eval.py, setup.py
Migração Python 3.10
Dados da tarefa: [T8432](https://multi.multidados.tech/web#id=8841&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T8432 - Migração da base de codigo para Python 3.10

addons/product/models/product_template.py
Ajusta método '_compute_default_code' módulo 'product'
- Mantém o default_code do product_template caso todas as variações tenham o mesmo default_code.
Dados da tarefa: [T8494](https://multi.multidados.tech/web?debug#id=8903&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T8494 - Erros ao importar itens da lista de preços no sistema

addons/stock/models/stock_quant.py
Ajusta domain 'owner_id' stock_quant módulo 'stock'
- Owner_id = False, pesquisar também o ID do Parceiro vinculado a empresa.
Dados da tarefa: [T8601](https://multi.multidados.tech/web#id=9010&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
PR(s) relacionado(s) (se houver): [1509](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1509)
=> T8601 - Erro: Estoque está Adicionando Owner nas movimentações gerando erros de saldos

addons/account/data/account_data.xml, addons/account/models/account_payment.py
* Adiciona sequencia para título descontado
Dados da tarefa: [T8581](https://multi.multidados.tech/web#id=8990&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T8581 - Criar a Opção de Descontar Título Manualmente

addons/product/models/product.py, addons/product/security/product_security.xml, addons/product/views/product_views.xml
- Remove campo de empresa dos produtos de Fornecedores
- [T8626](https://multi.multidados.tech/web?debug=1#id=9035&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T8626 - Verificar vinculo dos fornecedores aos produtos

addons/project/views/project_views.xml
Ajusta Kanban de Projetos módulo 'project'
Dados da tarefa: [T8643](https://multi.multidados.tech/web#id=9052&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
PR(s) relacionado(s) (se houver): [1537](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1537)
=> T8643 - Adicionar no Kanban de Projetos Tarefas e Agendas em Aberto

odoo/addons/base/models/ir_translation.py, odoo/modules/loading.py
[Adiciona no Unique Key da Tradução o módulo](https://github.com/multidadosti-erp/odoo/commit/e7a5446284d411c3bfebfee85e3168c33b397746)
[Atualiza Indice Unique da Tradução](https://github.com/multidadosti-erp/odoo/commit/c8b7c5f66aaf7ae35eeb88983e51ad11d668e214) 
- Obs.: Após a atualização reverter esse commit.
Dados da tarefa: [T8712](https://multi.multidados.tech/web?#id=9121&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T8712 - Ajustar Tradução do Odoo (Core) - Mistura Módulos

odoo/addons/base/views/res_partner_views.xml
Adiciona name page "Contacts & Addresses" módulo 'base'
Dados da tarefa: [T8736](https://multi.multidados.tech/web?#id=9145&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
[230](https://github.com/multidadosti-erp/others-addons/pull/230)
[961](https://github.com/multidadosti-erp/multidadosti-private-addons/pull/961)
[514](https://github.com/multidadosti-erp/multidadosti-financial-addons/pull/514)
[179](https://github.com/multidadosti-erp/multidadosti-web-addons/pull/179)
[86](https://github.com/multidadosti-erp/multidadosti-packages-addons/pull/86)
[1584](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1584)
=> T8736 - Ajustar Importação de Clientes do sistema PhonoSystem

addons/project/views/project_views.xml
- Ajuste em Form de Projetos, posicionamento na visualização de campos
- [T8673](https://multi.multidados.tech/web?#id=9082&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [l10n_br](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1595)
- [private-addons](https://github.com/multidadosti-erp/multidadosti-private-addons/pull/964)
=> T8673 - Criar Visão da Dash para Contratos

addons/mail/models/mail_thread.py
- Corrige validação de email na hora de montar o log
- O email pode ser obtido pelo usuário caso haja inconsistencia com o parceiro.
- [T8778](https://multi.multidados.tech/web?#id=9187&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [private-addons](https://github.com/multidadosti-erp/multidadosti-private-addons/pull/967)
=> T8778 - Ajustes na Nova Tela de Dash de Eventos do Contrato

addons/web/static/src/js/chrome/abstract_web_client.js, odoo/models.py
- Ajuste no efeito de notificação Web.Client
- Cria o widget JS de notificação trocando o retorno de `kind` para `type`, fazendo com que o módulo `oca/web/web_notify` renderize corretamente os ícones e a cor da notificação.
- [T8755](https://multi.multidados.tech/web?#id=9164&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [oca/web](https://github.com/multidadosti-erp/web/pull/15)
- [private-addons](https://github.com/multidadosti-erp/multidadosti-private-addons/pull/966)
=> T8755 - Contratos nao estão atualizando/gerando os evento automaticamente - valores sem atualização automática

addons/stock/i18n/pt_BR.po, addons/stock/i18n/stock.pot, addons/stock/models/stock_location.py
Adiciona Verificação de Saldo para Inativar Localização módulo 'stock'
- Adiciona uma nova verificação para bloquear a Inativação da Localização do Estoque caso tenha produtos com Saldo > 0.
- Atualiza tradução pt_br do módulo.
Dados da tarefa: [T8799](https://multi.multidados.tech/web?debug#id=9208&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T8799 - Sistema esta Deixando Inativar Estoques com Saldo dos Produtos

addons/calendar/models/calendar.py
Ajusta Criação do Calendário módulo 'calendar'
- Verifica o user_id para não ficar False.
Dados da tarefa: [T8865](https://multi.multidados.tech/web#id=9274&action=328&model=project.task&view_type=form&menu_id=223)
=> T8865 - O sistema não esta definindo o proprietario na inclusao da atividade

addons/base_vat/__manifest__.py, addons/crm/tests/test_new_lead_notification.py, addons/project/tests/test_project_flow.py, addons/test_mail/tests/__init__.py, addons/test_mass_mailing/tests/__init__.py, addons/test_mass_mailing/tests/test_blacklist.py, addons/test_mass_mailing/tests/test_mailing_internals.py, odoo/addons/base/models/res_partner.py, odoo/addons/base/tests/test_base.py, odoo/addons/base/tests/test_mail.py, odoo/addons/test_converter/tests/test_html.py, odoo/tools/mail.py
Corrige incompatiblidade dos testes com o python 3.10
Dados da tarefa: [T8873](https://multi.multidados.tech/web#id=9282&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T8873 - Ajustes de compatibilidade nos testes

addons/crm/views/crm_lead_views.xml
- Muda limite de registros no Pipeline CRM (causando lentidão)
- [T8853](https://multi.multidados.tech/web?#id=9262&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [l10n_br](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1634)
- [private-addons](https://github.com/multidadosti-erp/multidadosti-private-addons/pull/982)
- [report-addons](https://github.com/multidadosti-erp/multidadosti-report-addons/pull/337)
=> T8853 - Termo de Empréstimo

odoo/models.py
Adiciona novo parametro metodo 'user_has_groups' no 'models.py'
- Adiciona parametro: group_ids, permitindo assim o envio dos ids do grupo para pesquisar direito de acesso do usuário.
Dados da tarefa: [T8937](https://multi.multidados.tech/web?debug#id=9346&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
PR(s) relacionado(s) (se houver): [26](https://github.com/multidadosti-erp/social/pull/26)
=>  T8937 - Criar Verificação de Acesso da Atividade ao MODEL que esta vinculada

addons/product/views/product_views.xml
Ajusta Campo 'description' módulo 'product'
- Adiciona widget=HTML
Dados da tarefa: [T9068](https://multi.multidados.tech/web?#id=9477&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
PR(s) relacionado(s) (se houver): [1692](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1692)
=> T9068 - Adicionar as Anotações Internas dos Produtos nos Itens do Orçamento

odoo/models.py
Adiciona nova funcionalidade metodo 'read_group'
- fields_list_computed: Novo parametro para adicionar a lista de campos computed para totalizar.
Dados da tarefa: [T9067](https://multi.multidados.tech/web?#id=9476&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
PR(s) relacionado(s) (se houver): [1693](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1693)
=> T9067 - Incluir somatória para a coluna " Taxas Excluídas"

addons/account/models/account_invoice.py
Ajusta Código para uma melhor performance na gravação módulo 'account'
- Também documentado os métodos para uma melhor identificação.
Dados da tarefa: [T9080](https://multi.multidados.tech/web?#id=9489&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
[1700](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1700)
[1019](https://github.com/multidadosti-erp/multidadosti-private-addons/pull/1019)
=> T9080 - Melhorar a Performance da Fatura

addons/account/models/account_invoice.py
Corrige Erro módulo 'account'
- Adicionado o .ID para enviar o parametro correto.
Dados da tarefa: [T9109](https://multi.multidados.tech/web#id=9518&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T9109 - Erro ao acessar faturas pelo parceiro

addons/account/models/account.py, addons/account/models/account_invoice.py
Ajusta Atualização dos Impostos módulo 'account'
Dados da tarefa: [T9124](https://multi.multidados.tech/web#id=9533&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
PR(s) relacionado(s) (se houver): [1712](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1712)
=> T9124 - Imposto duplicado ao Editar fatura vinda de Contrato

addons/account/models/account_payment.py
Adiciona Método 'check_invoice_open' módulo 'account'
- Método adicionado para adicionar novas verificações em heranças nos módulos da localização br.
Dados da tarefa: [T9110](https://multi.multidados.tech/web#id=9519&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
PR(s) relacionado(s) (se houver): [1728](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1728)
=> T9110 - Título Descontado ao ser estornado não volta para o Status Título Descontado

addons/product/i18n/product.pot
- Inclui traduções em .pot do módulo "product"
- [T9139](https://multi.multidados.tech/web?#id=9548&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
PRs anteriores relacionados:
- [core](https://github.com/multidadosti-erp/odoo/pull/339)
- [private](https://github.com/multidadosti-erp/multidadosti-private-addons/pull/1030)
=> T9139 - Criar Tabela de Preço por Item relacionado ao Cliente

addons/account/models/account_invoice.py
Ajusta Metodo Compute p/ Cálculo Parcelas módulo 'account'
- Ajusta o tamanho do result e documenta para evitar erros.
Dados da tarefa: [T9192](https://multi.multidados.tech/web?#id=9601&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
[1748](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1748)
[1033](https://github.com/multidadosti-erp/multidadosti-private-addons/pull/1033)
=> T9192 - Adicionar opção Condição de Pagamento para Tratar Data do Faturamento do Contrato

addons/account/models/account_invoice.py
Corrige seleção de unidade de medida para fatura de fornecedor
Faturas de fornecedor devem selecionar a unidade de compra quando um produto e selecionado.
Dados da tarefa: [T9013](https://multi.multidados.tech/web?#id=9422&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T9013 - Conversão de unidades de compra por fatura e importação de xml

addons/point_of_sale/models/pos_order.py
Ajusta método '_action_create_invoice_line' módulo 'point_of_sale'
- Adiciona a Empresa como Contexto, pois ao Utilizar o SUDO perde o usuário e a empresa logada. Forçando o envio da Empresa para Contexto para Criação das Linhas da Fatura.
Dados da tarefa: [T9255](https://multi.multidados.tech/web?debug=1#id=9664&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
PR(s) relacionado(s) (se houver): [1768](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1768)
=> T9255 - Erro no POS: Ao gerar Invoice do POS esta pegando empresa Errada nos Itens

addons/account/views/account_portal_templates.xml
- Ajusta visualização de faturas no portal
- Remove data de vencimento da lista (não utilizado).
- Adiciona classe para xpath na coluna do campo `state`.
- [T9085](https://multi.multidados.tech/web?#id=9494&action=323&active_id=61&model=project.task&view_type=form&menu_id=223) 
- [l10n_br](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1782)
- [financial-addons](https://github.com/multidadosti-erp/multidadosti-financial-addons/pull/532)
- [report-addons](https://github.com/multidadosti-erp/multidadosti-report-addons/pull/360)
=> T9085 - Alterações/Correções Portal

addons/account/models/account_invoice.py
Remove arredondamento no calculo do total da fatura
Dados da tarefa: [T9286](https://multi.multidados.tech/web#id=9695&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T9286 - Erro de Arredondamento do IR em NFs de Serviço

addons/hr_timesheet/views/hr_timesheet_views.xml
Remove atributo 'editable' da view tree da planilha de horas
Dados da tarefa: [T9185](https://multi.multidados.tech/web#id=9594&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T9185 - Alteração Tela de Inclusão de Horas (Planilha de Horas)

addons/website/models/website.py, odoo/api.py, odoo/http.py, odoo/tools/cache.py
Substitui 'getargspec' por 'getfullargspec' Python 3.10
- Modernização do Odoo 12 para Python 3.10+
Dados da tarefa: [T9412](https://multi.multidados.tech/web?debug#id=9821&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
PR(s) relacionado(s) (se houver): [373](https://github.com/multidadosti-erp/multidadosti-report-addons/pull/373)
=> T9412 - Erro ao Criar Consulta - Evoluir Validação
