multidadosti-erp/odoo

addons/product/data/product_demo.xml, addons/product/tests/common.py, addons/purchase/test/fifo_price.yml, addons/purchase/test/fifo_returns.yml, addons/website_sale/data/demo.xml
**Restringe a criação de un. de medida e o registro duplicado**
- Retirado o create/edit do form de vendas
- Não é mais possível criar uma unidade de medida que já exista
[T2077](https://multi.multidadosti.com.br/web#id=2486&view_type=form&model=project.task&action=323&active_id=61)
Tabela: product_uom
Campos duplicados: 20, 21, >=39
=> T2077 - Apagar registros de Unidades de Medida Iguais

addons/sale/tests/test_sale_order.py
* [REF] Comenta teste incompativel com localizacao
O seguinte teste inserido aqui é incompatível com a localização: https://github.com/odoo/odoo/pull/35294
PR relacionado: https://github.com/multidadosti-erp/odoo-brasil-addons/pull/281
[T3227](https://multi.multidadosti.com.br/web#id=3636&view_type=form&model=project.task&action=323&active_id=61)
=> T3227-Corrigir erro de l10n_br após atualização

addons/account/tests/__init__.py, addons/l10n_generic_coa/tests/__init__.py
* [FIX] Desabilita teste incompatíveis com a localização
Ajustes nos testes do 'account' para que funcionem com o 'br_account'
após a migração
=> T3647-l10n_br / br_account

addons/purchase_stock/tests/__init__.py
* [IMP] Desabilita teste incompativel com 'abs_invoice_cancel_reason'
O modulo 'abs_invoice_calcel_reason' altera o comportamento do cancelamento
da fatura, invalidando o teste
[T3619](https://multi.multidadosti.com.br/web?#id=4028&view_type=form&model=project.task&action=323&active_id=61)
=> T3619-others / others-addons / abs_invoice_cancel_reason

addons/mail/i18n/pt_BR.po
[MIG] Atualiza tradução PT_BR ao modulo 'mail' do Core do Odoo 12
[T3882](https://multi.multidadosti.com.br/web?#id=4291&view_type=form&model=project.task&action=323&active_id=61)
=> T3882-Traduzir o Modulo "Mail" do Core - Odoo 12

addons/mail/i18n/pt_BR.po
[MIG] Atualiza tradução PT_BR ao modulo 'mail' do Core do Odoo 12
[T3882](https://multi.multidadosti.com.br/web?#id=4291&view_type=form&model=project.task&action=323&active_id=61)
--
=>  T3882-Traduzir o Modulo "Mail" do Core - Odoo 12

addons/sale/i18n/pt_BR.po
[MIG] Atualiza tradução de 'sale' para 12.0
[T3880](https://multi.multidadosti.com.br/web#id=4289&view_type=form&model=project.task&action=323&active_id=61)
=> T3880-Traduzir o Modulo "Sale" do Core - Odoo 12

addons/crm/i18n/pt_BR.po
[MIG] Atualiza tradução de 'crm' para 12.0
[T3858](https://multi.multidadosti.com.br/web#id=4267&view_type=form&model=project.task&action=323&active_id=61)
=> T3858-Traduzir o Modulo CRM do Core - Odoo 12

addons/note/i18n/pt_BR.po
[MIG] Atualiza tradução PT_BR modulo 'note' Odoo 12
[T3899](https://multi.multidadosti.com.br/web?#id=4308&view_type=form&model=project.task&action=323&active_id=61)
=> T3899-Traduzir o Modulo "NOTE" do Core - Odoo 12

addons/account/i18n/pt_BR.po
[MIG] Atualiza tradução de 'account' para 12.0
[T3879](https://multi.multidadosti.com.br/web#id=4288&view_type=form&model=project.task&action=323&active_id=61)
=> T3879-Traduzir o Modulo "Account" do Core - Odoo 12

addons/mail_bot/i18n/pt_BR.po
[MIG] Acerta tradução PT_BR  modulo 'mail_bot' para Odoo 12
[T3945](https://multi.multidadosti.com.br/web?#id=4354&view_type=form&model=project.task&action=323&active_id=61)
=> T3945-Traduzir Modulo: MAIL_BOT Odoo 12

addons/account/i18n/pt_BR.po
- Acerta tradução pt_br modulo 'account' Odoo 12
[T3958](https://multi.multidadosti.com.br/web?debug#id=4367&view_type=form&model=project.task&action=323&active_id=61)
=> T3958-Acerto na tradução pt_br modulo 'account' Odoo 12

addons/crm/i18n/pt_BR.po, addons/sale_crm/i18n/pt_BR.po
- Acerta tradução pt_br modulo 'crm' Odoo 12
- Acerta tradução pt_br modulo 'sale_crm' Odoo 12
[T3956](https://multi.multidadosti.com.br/web?debug#id=4365&view_type=form&model=project.task&action=323&active_id=61)
=> T3956-Acerto de tradução modulo 'crm' e 'sale_crm' do core

addons/stock/i18n/pt_BR.po
[IMP] Traduz módulo "stock" do core
[T3974](https://multi.multidadosti.com.br/web#id=4383&view_type=form&model=project.task&action=323&active_id=61)
=> T3974-Acertar tradução PT_BR módulo 'inventory' do Odoo 12

addons/sale/i18n/pt_BR.po
[MIG] Acerta tradução pt_br modulo 'sale' Odoo 12
[T3998](https://multi.multidadosti.com.br/web?#id=4407&view_type=form&model=project.task&action=323&active_id=61)
=> T3998-Acertar Tradução modulo 'Sale' Odoo 12

addons/base_import/static/src/js/import_action.js
[IMP] Habilita campo 'Criar caso não exista' no modulo 'Base Import' 
- Habilita campo mesmo sem Debug setado
[T4413](https://multi.multidadosti.com.br/web?#id=4822&view_type=form&model=project.task&action=323&active_id=61)
PR Relacionado: [402](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/402)
=> [IMP] Habilita campo 'Criar caso não exista' no modulo 'Base Import'

odoo/addons/base/security/base_security.xml
[IMP] Substitui Regra MultiCompany padrão do Odoo para 'res_users'
[T4672](https://multi.multidadosti.com.br/web?#id=5081&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T4672 - Adicionar no Odoo - MultiCompany nos Filtros para os Usuários

addons/stock/models/stock_rule.py
[FIX] Adiciona IF = 'product' para Regra de Stock modulo 'stock'
- Adicionado if product_id.type == 'product' para verificação da regra
do Estoque (Compra ou Transferência)
Obs.: Isso porque o type = 'consu' não controla saldo de Estoque, então
não precisa verificar a regra.
[T4765](https://multi.multidadosti.com.br/web?debug=#id=5174&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T4765 - Erro: Não deixa confirmar Pedido/Orçamento com Produto para Venda

odoo/addons/base/i18n/pt_BR.po
- [IMP] Corrige erro de português de 'clivar' para 'clicar'
- [T4855](https://multi.multidadosti.com.br/web?#id=5264&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> Corrige erro de português na mensagem de erro

addons/web/static/src/xml/web_calendar.xml
[IMP] Atualiza visão padrão do calendario no modulo 'web'
- Remove linha dos horários, com o objetivo de otimizar o espaço
utilizado pelos cards das agendas, seguindo inclusive o padrão
do outlook e thunderbird.
- Adiciona ao widget de image também o texto do campo, facilitando
a identificação quando utilizado.
Dados da tarefa: [T4985](https://multi.multidadosti.com.br/web?#id=5394&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
PR(s) relacionado(s): [609](https://github.com/multidadosti-erp/multidadosti-private-addons/pull/609)
Antes:
Depois:
=> T4985 - Melhorar a Visualização da Agenda das Fono (Ativiidade) vs Calendário

addons/account/views/account_payment_view.xml
- [IMP] Tira o submenu 'Registrar Pagamentos' do menu 'Ações'
- [T4974](https://multi.multidadosti.com.br/web?#id=5383&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T4974 - REGISTRAR PAGAMENTOS

addons/calendar/views/calendar_views.xml
- [IMP] Desabilita a função de abrir o formulário como popup
- [T4999](https://multi.multidadosti.com.br/web?#id=5408&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T4999 - Abrir a tela de reunião como formulario atualmente o sistema a abre como dialogo

addons/web/static/src/js/fields/basic_fields.js, addons/web/static/tests/fields/basic_fields_tests.js
[FIX] web: do not allow to edit priority field if readonly
if readonly attribute is given on priority widget then priority widget should
not be clickable and hover effect should be removed so that user can easily
understand that field is readonly.
task-2339680
closes odoo/odoo#57732
Signed-off-by: Aaron Bohy (aab) <aab@odoo.com>
Dados da tarefa: [T5082](https://multi.multidadosti.com.br/web?#id=5491&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
PR(s) relacionado(s) (se houver): [535](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/555)
=> T5082 - Erro: Não está gravando a Prioridade das Oportunidades

addons/crm/views/crm_lead_views.xml
[IMP] Adiciona "force_save" XML/Field "priority" modulo "crm"
- Adiciona no XML a tag force_save, para forçar a gravação do campo
priority, pois em algumas situações ele fica readonly e assim bloqueia
a gravação.
Dados da tarefa: [T5135](https://github.com/multidadosti-erp/odoo/compare/develop...multidadosti-erp:develop-T5135?expand=1)
PR(s) relacionado(s) (se houver): [570](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/570)
=> T5135 - Lista de Atividades não grava prioridade

addons/product/models/product_template.py, addons/sale/models/product_template.py
[IMP] Adiciona '_onchange_type' modulo 'product'
- Adiciona Metodo base _onchange_type para futuras heranças
[IMP] Adiciona super metodo '_onchange_type' modulo 'sale' 
- Adiciona o metodo 'Super' para chamar o metodo Base do modulo
'Product'
Obs.: Isso para Corrigir as Heranças do Campo: 'Type'
Dados da tarefa: [T5262](https://multi.multidadosti.com.br/web?debug#id=5671&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
PR(s) relacionado(s) (se houver): [595](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/595)
=> T5262 - Erro: Não está deixando cadastrar KIT de Serviço

addons/note/__manifest__.py, addons/note/models/note.py, addons/note/security/note_security.xml
- [FIX] Corrige erro de permissão ao atribuir uma anotação a outra pessoa
- [T5327](https://multi.multidadosti.com.br/web?#id=5736&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [l10n_br](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/611)
=> T5327 - erro de permissão ao criar anotação de projeto

odoo/tools/mimetypes.py
[FIX] Adiciona tipo arquivo XML, separado do SVG modulo 'tools'
- Adiciona ELSE na verificação da tag <svg para diferenciar arquivos
XML normais (tipo de NF) do XML do tipo SVG.
Dados da tarefa: [T5386](https://multi.multidadosti.com.br/web#id=5795&model=project.task&view_type=form&menu_id=)
=> T5386 - Erro ao importar XML de compras

addons/website_sale/tests/test_website_sale_product_attribute_value_config.py
* [FIX] Corrige tipo da taxa de acordo com o 'price_include'
Para usar 'price_include' temos que usar o calculo do tipo 'division'. O tipo de calculo 'percent' é usado apenas quando o 'price_include' é falso.
Dados da tarefa: [T5404](https://multi.multidadosti.com.br/web#id=5813&action=323&active_id=61&model=project.task&view_type=form&menu_id=)
=> T5404 - Lançamentos de diário incorretos com imposto 'Incluído no Preço'

odoo/addons/base/models/ir_model.py
[FIX] Adiciona acesso total a 'ir.model' para evitar erros de permssão
- Adiciona "or model == 'ir.model'" ao IF para dar acesso total,
para corrigir o problema de acesso de permissão do Odoo na model
'ir.model'
Alteração para corrigir a Produção até descobrirmos o que realmente aconteceu.
=> [FIX] Adiciona acesso total a 'ir.model' para evitar erros de permssão

odoo/models.py
[FIX] Adiciona nova verificação IF de pesquisa em 'models.py'
- Adiciona verificação de conteudo para iniciar um search na tabela
Evitando assim erro na pesquisa por não tem conteudo nenhum.
Dados da tarefa: [T5549](https://multi.multidadosti.com.br/web#id=5958&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
PR(s) relacionado(s) (se houver): [654](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/654)
=> T5549 - Erro: Importação de Clientes, fica até dar timeout

addons/point_of_sale/i18n/pt_BR.po, addons/point_of_sale/models/product.py, addons/point_of_sale/static/src/js/db.js, addons/point_of_sale/static/src/js/models.js, addons/point_of_sale/views/product_view.xml
- [IMP] Adicionando campo da categoria 'Root' aos produtos
- Campo criado para definir se o produto irá aparecer na tela da
categoria principal dos produtos no POS. Será possivel alterar
o campo no form do 'product.template'
- [T5559](https://multi.multidadosti.com.br/web?#id=5968&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [l10n_br](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/657)
=> T5559 - Acertar a tela do POS que não mostra todos os produtos no Filtro

addons/product/i18n/pt_BR.po, addons/purchase/i18n/pt_BR.po
- [IMP] Corrige a tradução de 'Vendors'
- [T5570](https://multi.multidadosti.com.br/web#id=5979&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [l10n_br](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/659)
=> T5570 - Acertar tradução de "parceiros" para "fornecedores no cadastro de Produto na Aba Compra

addons/stock/i18n/pt_BR.po, addons/stock/views/stock_inventory_views.xml
* [IMP] Melhora descrição do filtro na tela de inventario de estoque
Adiciona uma texto mais descrivo para o checkbox de adicionar produtos esgotados e melhora o posicionamento do campo na tela.
Dados da tarefa: [T5597](https://multi.multidadosti.com.br/web#id=6006&action=323&active_id=61&model=project.task&view_type=form&menu_id=
)
PR relacionado: https://github.com/multidadosti-erp/odoo-brasil-addons/pull/677
=> T5597 - Criação de inventário não adiciona produtos sem estoque

addons/account/views/account_invoice_view.xml
- [IMP] Adiciona atributos 'name' nas tags para facilitar o XPATH
- [T5710](https://multi.multidadosti.com.br/web?#id=6119&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [l10n_br](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/716)
=> T5710 - incluir valor financeiro na tela de faturas de fornecedores

addons/sale_mrp/tests/__init__.py
[FIX] Remove 'required=True' em 'product.attribute' modulo 'sale'
- Removido required=True do campo 'type' em 'product.attribute'
do modulo 'sale' que esta conflitando com o modulo 'mrp' nos testes.
Dados da tarefa: [T5773](https://multi.multidadosti.com.br/web?#id=6182&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
PR(s) relacionado(s) (se houver): [728](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/728)
=> T5773 - Adicionar o modulo MRP para uso em clientes

odoo/addons/base/models/res_config.py
=> [FIX] Corrige sintaxe de código python

addons/account/models/account_move.py
[IMP] Adiciona 'move_id' raise modulo 'account'
- Adiciona move_id na mensagem para facilitar a identificação de
qual registro esta com diferença.
Dados da tarefa: [T5811](https://multi.multidadosti.com.br/web?debug#id=6220&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T5811 - Adicionar Id do move na mensagem de erro para facilitar a Identificação

addons/point_of_sale/models/res_partner.py, addons/point_of_sale/static/src/js/models.js
- [FIX] Corrigindo filtro de Parceiros no POS
- Foi adicionado o comportamento de criar 2 campos para o objeto do POS para serem utilizados em outros lugares. Os campos são criados ao iniciar a model de 'res.partner'
Descrição do PR
- [T5850](https://multi.multidados.tech/web?debug=#id=6259&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [l10n_br](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/759)
=> T5850 - O sistema esta filtrando de forma errada os clientes no POS

addons/point_of_sale/i18n/pt_BR.po, addons/point_of_sale/static/src/js/screens.js
- [FIX] Erro ao criar cliente pelo POS
- Adiciona comportamento para atualizar domínio dos clientes que podem ser vistos pelo vendedor.
- Adiciona funcionalidade de mostrar aviso que o cliente foi cadastrado e esconde a tela de cadastro após finalizar o cadastro.
- [T5903](https://multi.multidados.tech/web?debug=#id=6312&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [l10n_br](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/777)
=> T5903 - Erro ao tentar efetuar o cadastro de um novo cliente atraves do POS

odoo/modules/registry.py
[IMP] Adiciona tratamento para tabela externas modulo 'registry.py'
- Adiciona tratamento para ignorar tabelas iniciadas com
= 'x_ks_cr'
Dados da tarefa: [T5958](https://multi.multidados.tech/web?debug#id=6367&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T5958 - Erro no Odoo ref as Tabelas/Views criadas pelo Modulo ks_custom_report

addons/web/static/lib/tempusdominus/tempusdominus.js
- [FIX] Corrige erro ao setar uma data no JavaScript
- A linha editada estava dentro do if, e em casos que o bloco do 'else' era executado ao inves do 'if' não era executado, dava erro.
- [T5975](https://multi.multidados.tech/web#id=6384&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [oca/project](https://github.com/multidadosti-erp/project/pull/5)
- [private-addons](https://github.com/multidadosti-erp/multidadosti-private-addons/pull/690)
- [public-addons](https://github.com/multidadosti-erp/multidadosti-addons/pull/600)
- [l10n_br](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/800)
=> T5975 - Melhorias nas Subtarefas do Projeto

addons/web/static/src/js/services/crash_manager.js
- [FIX] Erro ao usar o RedirectWarning perde o menu de referência
- Ao utilizar o RedirectWarning, o sistema permite que na mensagem de erro, aparece um botão para o usuário realizar uma action. Mas ao usuário realizar a action, o menu superior era perdido, fazendo com que o usuário não pudesse mais navegar pelo módulo, sem trocar de módulo antes.
- [T5580](https://multi.multidados.tech/web#id=5989&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [l10n_br](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/838)
=> T5580 - Erro ao importar XML de compras (Valor Total e Parcelas)

addons/web/static/src/js/views/list/list_editable_renderer.js
- [IMP] Verificação se a linha poderá ser removida do campo X2Many
- Adiciona verificação para identificar se a linha que será renderizada no widget de campo X2Many, deverá ter o ícone de 'delete' ou 'unlink'.
- [T6126](https://multi.multidados.tech/web?#id=6535&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [l10n_br](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/854)
=> T6126 - Alterar Widget da lista X2Many para aplicar o delete dinâmicamente nas linhas

odoo/addons/base/models/ir_model.py
- [IMP] Adiciona nome do usuário no log de AccessError
- [T6044](https://multi.multidados.tech/web#id=6453&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [formio](https://github.com/multidadosti-erp/odoo-formio/pull/14)
- [l10n_br](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/851)
=> T6044 - Criar restrição para acesso a formulário pelo portal

addons/crm/tests/test_crm_activity.py, addons/product_expiry/tests/test_stock_production_lot.py
- [FIX] Comenta testes para não dar erro ref a qtd de atividades
- [T6245](https://multi.multidados.tech/web#id=6654&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [private-addons](https://github.com/multidadosti-erp/multidadosti-private-addons/pull/720)
- [oca/social](https://github.com/multidadosti-erp/social/pull/9)
=> T6245 - Corrigir testes ref. as atividades no Runbot

addons/mail/models/mail_template.py
- [IMP] Permite enviar um relatório por contexto para envio de email
- Ao gerar um email, é possível que seja gerado com um outro relatório anexado sem ser o relatório que está relacionado ao 'mail.template'.
- Para utilizar um relatório diferente do padrão do modelo, é necessário ter no contexto o id do relatório a ser anexado no modelo:
`{'report_template_to_generate_email' : id_do_relatório}`
- [T6239](https://multi.multidados.tech/web#id=6648&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [l10n_br](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/892)
- [lab88-addons](https://github.com/multidadosti-erp/lab88-addons/pull/67)
- [report-addons](https://github.com/multidadosti-erp/multidadosti-report-addons/pull/233)
=> T6239 - Reorganização de impressão

odoo/fields.py, odoo/models.py
[FIX] Ajusta Fields e Models para tratar 'compute_sudo'
- Adiciona 'Model' verificação de contexto para aplicar as regras
de visualização do conteudo das tabelas.
Dando a opção para forçar a visualização do resultado do banco de
dados ignorando a regra do Odoo.
- Adiciona nos atributos dos campos a tag compute_sudo
Dados da tarefa: [T6324](https://multi.multidados.tech/web?#id=6733&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
PR(s) relacionado(s) (se houver): [426](https://github.com/multidadosti-erp/multidadosti-financial-addons/pull/426)
=> T6324 - Erro: Plano de Contas com mais de uma Empresa

addons/pos_cache/__manifest__.py
- [FIX] Bloqueia a instalação do módulo 'POS_CACHE' para não dar erro
- O módulo causa incompatibilidade com o módulo 'br_pos_base', então seu conteúdo foi passado para o módulo 'br_pos_base' e alterado o que deveria lá mesmo.
- [T6366](https://multi.multidados.tech/web#id=6775&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [l10n_br](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/915)
=> T6366 - Incluir no modulo br_pos_base - Cache de Clientes/Produtos

addons/web/static/src/js/views/form/form_renderer.js
- [FIX] Adiciona tag para corrigir o statusbar sobrepondo elementos
- A tag z-index é verificada para determinar se o statusbar deve ter o estilo z-index = 0.
- [T6514](https://multi.multidados.tech/web#id=6923&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [l10n_br](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/979)
=> T6514 - Menu sobrepondo informações

addons/sale_stock/models/sale_order.py
[FIX] Adiciona SUDO metodo cancel sale order modulo 'sale_stock'
- Adiciona sudo para evitar erros de bloqueio de permissão ref ao
stock.
Dados da tarefa: [T6553](https://multi.multidados.tech/web#id=6962&action=328&model=project.task&view_type=form&menu_id=223)
=> T6553 - Verificação do erro ao tentar cancelar pedido de venda

addons/crm/models/crm_lead.py
[FIX] Remove context 'team_id' metodo 'action_schedule_meeting' modulo 'crm'
- Remove contexto default_team_id': self.team_id.id para a criação
do calendar.event.
Obs.: Campo não existe no Odoo e ao utilizarmos o modulo da
OCA/mail_activity_team ocorreu conflito.
Dados da tarefa: [T6582](https://multi.multidados.tech/web?debug=#id=6991&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T6582 - Equipe de atividades

addons/stock/models/stock_production_lot.py
Comentado _sql_constraints 'stock.production.lot' modulo 'stock'
- Comentado pela Multidados, pois adicionamos o campo COMPANY_ID e o _sql_constraints
tem que considerar.
Obs: Adicionado no modulo da OCA/stock_production_lot_multi_company
_sql_constraints = [
('name_ref_uniq', 'unique (name, product_id)', 'The combination of serial number and product must be unique !'),
]
Dados da tarefa: [T6686](https://multi.multidados.tech/web?#id=7095&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T6686 - Erro no Core do Odoo por não tratar lot por empresa

addons/product/models/product.py, addons/stock_account/models/stock.py
[Adiciona Index=True em campos do modulo 'product'](https://github.com/multidadosti-erp/odoo/commit/a851c6feb56c62f061829ac84fcbde1ec6e3ce39) 
- Adicionado tag Index=True para melhor performance.
[Corrige regravação de price_unit no modulo 'stock_account'](https://github.com/multidadosti-erp/odoo/commit/7e70d2600a9b7111d0ccb705bf21d215f1941c34) 
- Adiciona if not self.price_unit para evitar gravar erroneamente
o valor do custo do produto na movimentação, pois o valor tem que
vir do último pedido ou NF não do cadastro.
Dados da tarefa: [T6718](https://multi.multidados.tech/web?#id=7127&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
PR(s) relacionado(s) (se houver): [1056](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1056)
=> T6718 - Criação dos Campos de Custo Medio do Item e Valor Medio de Vendas

odoo/models.py
Adiciona novo método 'check_access_rule_bool' módulo 'odoo'
- Método para retornar True ou False de Acordo com a verificação do método original 'check_access_rule'
Dados da tarefa: [T6851](https://multi.multidados.tech/web?#id=7260&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
[1088](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1088)
[614](https://github.com/multidadosti-erp/multidadosti-addons/pull/614)
[478](https://github.com/multidadosti-erp/multidadosti-financial-addons/pull/478)
=> T6851 - Erro no processamento Queue no Retorno de CNAB

addons/point_of_sale/static/src/js/models.js
- Corrige erro de produto com posição fiscal no POS
- [T6879](https://multi.multidados.tech/web#id=7288&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T6879 - Erro no POS ao Tentar Incluir Produto com Posição Fiscal Definida

addons/stock/views/product_views.xml
Adiciona Regra Visible campo 'traceability' módulo 'stock'
- Deixar Invisible se o campo type não for 'product'
Dados da tarefa: [T6936](https://multi.multidados.tech/web?#id=7345&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
PR(s) relacionado(s) (se houver): [1117](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1117)
=> T6936 - Adicionar Melhorias ao Calcular os Custos

odoo/fields.py, odoo/models.py
Adiciona tag: dynamic_default na definição de Campos.
- Objetivo é executar o default por registro, pois no padrão do odoo, no update ele executava uma unica vez e gravação o mesmo valor para todos os registros.
Dados da tarefa: [T7033 ](https://multi.multidados.tech/web?#id=7442&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T7033 - Criar APIs: Cliente e Projeto

addons/mail/views/mail_activity_views.xml
Remove groups 'group_no_one' módulo 'mail'
- Remove dos campos: 'res_model_id' e 'decoration_type' para liberar o acesso para os usuários normais do sistema.
Dados da tarefa: [T7055 ](https://multi.multidados.tech/web#id=7464&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T7055 - Alguns tipos de Atividade não estão disponiveis para a inclusão de uma nova atividade

addons/product/models/product_pricelist.py, addons/sale/models/sale.py
* Adiciona verificação para manter preco unitario ao alterar quantidade
Em casos onde a tag 'uom_qty_change' esta presente no contexto (indica que o metodo foi chamado devido ao onchange de campo de quantidade) e a quantidade minima do produto na lista de preço é zero, nós mantemos o valor original do preço unitario. Isso impede que o valor de preco unitario inserido pelo usuario seja sobrescrito pelo valor da lista de preco quando a quantidade do produto e alterada no orçamento.
Dados da tarefa: [T7019](https://multi.multidados.tech/web#id=7428&action=323&active_id=61&model=project.task&view_type=form&menu_id=)
=> T7019 - INSTABILIDADE NO VALOR DO ITEM

addons/crm/i18n/crm.pot, addons/crm/i18n/pt_BR.po, addons/crm/models/crm_stage.py, addons/crm/views/crm_stage_views.xml, addons/hr_recruitment/i18n/hr_recruitment.pot, addons/hr_recruitment/models/hr_recruitment.py, addons/project/i18n/project.pot, addons/project/i18n/pt_BR.po, addons/project/models/project.py, addons/web/static/src/js/views/basic/basic_model.js, addons/website_event_track/i18n/website_event_track.pot, addons/website_event_track/models/event_track.py, odoo/models.py
[Adiciona opção de '_auto_fold' na View Kanban](https://github.com/multidadosti-erp/odoo/commit/a1203989847229107a53134f4f3a5bef8cfb46cb)
[Adiciona 'auto Fold' módulo 'crm'](https://github.com/multidadosti-erp/odoo/commit/af2d0ea9ed68f59a2006b695470d9d8f197e8fed) 
- Atualiza View Form e Tree
- Atualiza Tradução pt_br do módulo
[Corrige a Mensagem 'FOLD' módulo 'hr_recruitment'](https://github.com/multidadosti-erp/odoo/commit/05894bb1f072d1fabfdc665ee6eb14fc53da297a)
[Corrige a Mensagem 'FOLD' módulo 'project'](https://github.com/multidadosti-erp/odoo/commit/b1943aa8cfd7f2d84b3fa72f3d4ba1bbe696a68d)
[Corrige a Mensagem 'FOLD' módulo 'website_event_track'](https://github.com/multidadosti-erp/odoo/commit/f2fec6b85228ec26a6102bd19c1bb5011bfdf337)
Dados da tarefa: [T7112 …
=> T7112 - Criar modo que não demonstre estagios vazios ao pesquisar dados nas oportunidades

addons/stock/views/stock_picking_views.xml
Ajusta view 'view_picking_form' módulo 'stock'
- Ajusta para uma melhor visualização do formulário de separação dos produtos.
Dados da tarefa: [T7111 ](https://multi.multidados.tech/web#id=7520&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
PR(s) relacionado(s) (se houver): [1166](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1166)
=> T7111 - Importação do XML trazer toda a descrição par identificar o Nr de Série

addons/mail/models/mail_activity.py, addons/mail/static/src/js/activity.js, addons/mail/static/src/scss/mail_activity.scss, addons/mail/static/src/xml/web_kanban_activity.xml, addons/purchase/i18n/pt_BR.po, addons/purchase/i18n/purchase.pot, addons/purchase/views/purchase_views.xml, addons/sale/i18n/pt_BR.po, addons/sale/i18n/sale.pot, addons/sale/views/sale_views.xml
[Adiciona widget="list_activity" módulo 'mail'](https://github.com/multidadosti-erp/odoo/commit/af4dcf537d881dfe34b64655c345e2d92e4e6ce0) 
- Objetivo poder visualizar a Próxima Atividade na Visão Tree.
[Adiciona Tree de Compras Prox Atividade módulo 'purchase'](https://github.com/multidadosti-erp/odoo/commit/98961bf1266f3093ea4d473bcb6e0404dea48dbd) 
- Atualiza tradução pt_br do módulo.
- Atualiza arquivo pot de traduções.
[Adiciona Tree de Compras Prox Atividade módulo 'sale'](https://github.com/multidadosti-erp/odoo/commit/18d824469d1468ed6e39c207231619ba7f55eb8b) 
- Atualiza arquivo pot de traduções.
[Ajusta CSS para dar destaque nos ICONES das Atividades módulo 'mail'](https://github.com/multidadosti-erp/odoo/commit/68fc19a740b3385b514010ca5bbb304205 …
=> T7197 - Adicionar a Funcionalidade do widget="list_activity" do Odoo 14 ao Odoo 12

addons/stock/models/stock_quant.py, addons/stock/tests/test_quant.py
Comentado Raise Saldo Reservado de Estoque módulo 'stock'
- Comentado até descobrir os cálculos para liberar os clientes de cancelarem separações não confirmadas.
Dados da tarefa: [T7215 ](https://multi.multidados.tech/web#id=7624&action=328&active_id=8250&model=project.task&view_type=form&menu_id=465)
=>  T7215 - Erro de estoque no Cancelamento de Separação

addons/account/i18n/pt_BR.po, addons/account/views/account_payment_view.xml
Ajusta Account Payment módulo 'account'
- Comenta Action do Core de Confirmação de Pagamento, pois não utilizamos o esse recurso do Odoo.
- Atualização tradução pt_br.
Dados da tarefa: [T7410](https://multi.multidados.tech/web?debug=#id=7819&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
[498](https://github.com/multidadosti-erp/multidadosti-financial-addons/pull/498)
[842](https://github.com/multidadosti-erp/multidadosti-private-addons/pull/842)
[1242](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1242)
=> T7410 - Criar mecanismo para a conciliação dos titulos pagos e recebidos

addons/sale_expense/tests/__init__.py
- Comenta testes do 'sale_expense' para não dar erro
- [T7467](https://multi.multidados.tech/web#id=7876&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [private-addons](https://github.com/multidadosti-erp/multidadosti-private-addons/pull/844)
- [l10n_br](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1251)
- [channel-addons](https://github.com/multidadosti-erp/multichannels-addons/pull/55)
=> T7467 - Lançar Despesas no Conta Corrente do Funcionário

addons/account/i18n/pt_BR.po, addons/account/views/account_payment_view.xml
Ajusta View 'view_account_payment_tree' módulo 'account'
- Ajusta as tags decoration
- Adiciona default_order na Tree
Dados da tarefa: [T7647 ](https://multi.multidados.tech/web?#id=8056&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
[1267](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1267)
[294](https://github.com/multidadosti-erp/multidadosti-report-addons/pull/294)
=> T7647 - Alterações Solicitadas pelo Cliente

addons/stock/models/stock_quant.py
Ajusta metodo '_unlink_zero_quants(self)' módulo 'stock'
- Adicionado no WHERE lot_id is null para não remover o produtos controlados por Número de Série e Lote.
Dados da tarefa: [T7716](https://multi.multidados.tech/web?debug=#id=8125&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T7716 - Odoo está apagando stock_quant dos lot zerados, causando problemas nos relatórios

odoo/import_xml.rng, odoo/tools/convert.py
Adiciona tag 'noupdate' no XML/Template módulo 'odoo'
- Adicionado para poder selecionar se o template deve ou não ser atualizado pelo odoo no update.
Dados da tarefa: [T7792](https://multi.multidados.tech/web?#id=8201&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
PR(s) relacionado(s) (se houver): [297](https://github.com/multidadosti-erp/multidadosti-report-addons/pull/297)
=> T7792 - Criar no modelo de relatório padrão Tag Clausulas para Configuração

addons/stock/models/stock_picking.py, addons/stock/views/stock_picking_views.xml
- Correções no módulo 'Stock'
- Remove onchange do lot para zerar a quantidade concluida e o lote caso tenha dado erro
- Remove dependência de campos 'show_reserved' e 'show_operation'
- [T7795](https://multi.multidados.tech/web#id=8204&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [l10n_br](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1290)
=> T7795 - Duplicação de itens

addons/mail/static/src/js/activity.js, addons/project_timesheet_holidays/tests/__init__.py
- Corrige erro quando atividade nao tem status
- O campo status foi adicionado no módulo da oca/social 'mail_activity_done', mas a verificação foi adicionada no core para facilitar.
- O módulo mail_activity_done sempre estará instalado nos ambientes dos clientes, mas trata para quando nao estiver.
- Foi percebido a necessidade da verificação quando criei um banco de testes e a funcionalidade sem o módulo 'mail_activity_done' intalado não estava correta.
- [T7811](https://multi.multidados.tech/web?#id=8220&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [oca/social](https://github.com/multidadosti-erp/social/pull/14)
- [l10n_br](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1296)
- …
=> T7811 - Ajustar o Módulo de Atividades

addons/account/models/account_invoice.py
Ajusta 'action_cancel' módulo 'account'
- Adiciona na lista de campos a limpar o 'reference'
Dados da tarefa: [T7582](https://multi.multidados.tech/web?debug#id=7991&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
PR(s) relacionado(s) (se houver): [1299](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1299)
=> T7582 - Entrada/validação NF 62553

addons/mail/models/mail_message.py, addons/mail/static/src/js/composers/chatter_composer.js
- Adiciona atributo '_noteSubgroup' no widget chatter composer
- O atributo foi adicionado para herança em outros modulos e alterar qual é o subtipo das mensagens de Anotações.
- Adiciona função para facilitar herança do widget de mensagens
- Os parâmetros passados para a função 'read' dentro da função message_format, foram substituidos por uma função para obtê-los, facilitando a herança em outros módulos.
- [T7806](https://multi.multidados.tech/web?#id=8215&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [l10n_br](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1303)
=> T7806 - Separar os Logs, Anotações e Mensagens

addons/account/views/account_invoice_view.xml
Ajusta 'journal_id' XML/Form Invoice módulo 'account'
- Ajustado a tag readonly para controlar através do status da invoice => attrs="{'readonly':[('state', '!=', 'draft')]}"
Dados da tarefa: [T7844](https://multi.multidados.tech/web?#id=8253&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
PR(s) relacionado(s) (se houver): [1305](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1305)
=> T7844 - Liberar a Alteração do Diário na Invoice de Compras

addons/mail/static/src/js/models/threads/thread.js
- Muda a quantidade de mensagens a mostrar no Thread (30 -> 60)
- [T7842](https://multi.multidados.tech/web?#id=8251&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [l10n_br](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1306)
=> T7842 - Ajustes no Widget Thread após a separação de mensagens e logs

addons/mail/models/mail_message.py, addons/mail/models/mail_thread.py, addons/mail/static/src/js/discuss.js, addons/mail/static/src/js/models/threads/document_thread.js, addons/mail/static/src/js/services/mail_document_thread_manager.js, addons/mail/static/src/js/thread_windows/abstract_thread_window.js
- Separação de mensagens por subtipos no Thread Widget
- para possibilitar o uso de carregar mais mensagens, o widget Thread foi modificado para separar os ids das mensagens por tipos.
- Entre os tipos utilizados no widget estão ['note', 'log', 'discussion']
- Adiciona tag para o thread que não deve colapsar subtipos
- No Widget Thread foi adicionado no 'br_mail' a opção de não colapsar os subtipos de mensagem, e é adicionado fixo ao ver as mensagens pelo módulo de mensagens e quando está com um bate-papo aberto.
- [T7847](https://multi.multidados.tech/web?#id=8256&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [l10n_br](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1311)
=> T7847 - Ajustes no Widget Thread "Mostrar Mensagens Antigas"

addons/mail/models/mail_message.py
- Corrige ordenação de mensagens ao Mostrar mais
- Corrige erro de 'Mostrar mensagens antigas'
- O erro ocorria porque tinham tipos de mensagens personalizados por módulos. O correto seria ao adicionar um novo subtipo, incluir ele no retorno da função de agrupamento das mensagens, porém, como ja existem varios subtipos criados, optamos por incluir como log esses subtipos que não forem incluídos no agrupamento.
- [T7873](https://multi.multidados.tech/web?#id=8282&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [l10n_br](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1316)
=> T7873 - Correções no chatter (Mostrar mais mensagens está aparecendo sempre)

addons/sales_team/models/crm_team.py, addons/sales_team/tests/test_default_team.py
- Corrige obtenção de Equipe de Vendas Padrão
- O método de obter a equipe de vendas padrão estava obtendo a equipe de forma errada. O search era feito corretamente, obtendo uma equipe dependendo da empresa do usuário ativo, e se ele é membro ou lider da equipe. Quando não obtinha nenhuma equipe, estava selecionando a equipe criada por padrão: 'sales_team.team_sales_department'
- [T7834](https://multi.multidados.tech/web?#id=8243&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T7834 - Sistema assumindo a equipe de vendas errada e não permite trocar para a correta

addons/web/static/src/js/views/list/list_renderer.js
- Habilita opção de não permitir ordenamento pelo campo na tree
- Por default o sortable é = True
- Adiciona código para verificar se o campo tem no atributo options a flag {'sortable': True}
- [T7954](https://multi.multidados.tech/web?#id=8363&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T7954 - Adicionar forma de impossibilitar o ordenamento em tree

addons/web/static/src/js/chrome/abstract_web_client.js
- Adapta webClient para Effect de notificação do usuário
- ao lançar um effect do tipo notification, lança uma notificação para o usuário.
- [T7945](https://multi.multidados.tech/web?#id=8354&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [l10n_br](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1344)
- [private-addons](https://github.com/multidadosti-erp/multidadosti-private-addons/pull/879)
=> T7945 - Faturar Devoluções de estoque pela tela do contrado (adicionar wizard)

addons/point_of_sale/models/pos_order.py, addons/point_of_sale/models/pos_session.py
- Adiciona campos para determinar se os pedidos sao ou existem devoluções
- O campo 'origin_order_id' indica o pedido que foi devolvido.
- O campo 'return_order_id' indica o pedido ref a devolução.
- [T7975](https://multi.multidados.tech/web?#id=8384&action=323&active_id=61&model=project.task&view_type=form&menu_id=)
- [l10n_br](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1348)
=> T7975 - Cancelamento de pedidos PDV - Conciliação financeira e Estoque.

addons/crm/models/crm_stage.py, addons/crm/views/crm_stage_views.xml
Ajusta XML e Campos módulo 'crm'
- Adiciona 'track_visibility' nos campos para Log
- Adiciona Header, Sheet e oe_button_box para melhor controle nas heranças
Dados da tarefa: [T8002](https://multi.multidados.tech/web?#id=8411&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
PR(s) relacionado(s) (se houver): [1361](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1361)
=> T8002 - Adicionar a opção de inativar estágios do CRM e Criação de Log

addons/crm/i18n/pt_BR.po, addons/crm/views/crm_lead_views.xml, addons/mail/i18n/pt_BR.po, addons/mail/static/src/xml/web_kanban_activity.xml, addons/stock/i18n/pt_BR.po, addons/stock/views/stock_move_views.xml, addons/stock/views/stock_picking_views.xml, odoo/addons/base/models/ir_ui_view.py, odoo/addons/base/rng/tree_view.rng
- Adiciona 'user' nos símbolos de contexto no render da View
- Quando alteramos o método 'session_info' para adicionar os campos do usuário no contexto, não era permitido utilizar em alguns locais, como no domain de tags filter.
- [T7995](https://multi.multidados.tech/web?#id=8404&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [l10n_br](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1364)
- [private-addons](https://github.com/multidadosti-erp/multidadosti-private-addons/pull/885)
- [muk](https://github.com/multidadosti-erp/muk-addons/pull/37)
=> T7995 - Melhorias no Multiphono (menus, testes)

addons/web/static/src/js/views/kanban/kanban_view.js, addons/web/static/src/scss/kanban_view.scss, addons/web/static/src/scss/primary_variables.scss
- Corrige erro da propriedade 'draggable' do kanban
- Adiciona no CSS estilo para um kanban de tamanho maior 'large' 
- Cria variável para definir um tamanho maior para kanban, assim como existe com o tamanho menor.
- Adiciona essa variável como valor para width da classe 'o_kanban_large_column'
- [T8161](https://multi.multidados.tech/web?#id=8570&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [oca/web](https://github.com/multidadosti-erp/web/pull/13)
- [l10n_br](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1399)
- [private-addons](https://github.com/multidadosti-erp/multidadosti-private-addons/pull/900)
=> T8161 - Melhorias no Módulo de Contrato de Serviço

addons/stock/views/stock_move_views.xml
Adiciona 'origin_returned_move_id' Contexto módulo 'stock'
- Adiciona o campo 'origin_returned_move_id' no contexto da inclusão do stock_move_lines.
Dados da tarefa: [T8227](https://multi.multidados.tech/web#id=8636&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
PR(s) relacionado(s) (se houver): [1410](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1410)
=> T8227 - Sistema permite retornar números de série diferente no retorno do estoque/locação

addons/hr_expense/i18n/pt_BR.po, addons/hr_expense/models/hr_expense.py, addons/hr_expense/tests/__init__.py, addons/hr_expense/views/hr_expense_views.xml, addons/sale_expense/tests/__init__.py
- Atualiza tradução do módulo de Despesas ('hr_expense')
- Comenta testes referente a Despesas (desenvolvimento futuro)
- Adiciona sicronização de despesas com relatórios de despesas
- Antigamente o campo que relacionava as despesas no relatório de despesas, era One2many, então o campo sheet_id na despesa (many2one) era sincronizado automaticamente. Com a mudança do campo para Many2many, foi necessária uma sincronização.]
- A sincronização é adicionada no create e write do relatório 'hr.expense.sheet', de modo a esperar que o relacionamento seja criado sempre a partir do relatório e não nas despesas.
- Organiza definição dos menus do módulo de despesas no arquivo XML
- Organiza estrutura do arquivo para facilitar visualização.
- Organiza sequência dos menus
- Adiciona menu específico de …
=> T8201 - Melhorias no Módulo de Despesas

addons/hr_expense/views/hr_expense_views.xml, addons/sale_expense/__manifest__.py, addons/sale_expense/models/__init__.py
- Ajustes em form de despesas 'hr_expense_view_form'    
- Organização de campos na tela.
- Esconde alguns campos.
- altera botão de criar relatório de despesa para criar todos os relatórios necessários em um só botão
- Comenta conteúdo do modulo 'sale_expense'
- [T8237](https://multi.multidados.tech/web?#id=8646&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [l10n_br](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1413)
- [channel-addons](https://github.com/multidadosti-erp/multichannels-addons/pull/77)
=> T8237 - Ajustes nas Despesas

addons/calendar/i18n/pt_BR.po, addons/calendar/models/calendar.py
Adiciona Método para Facilitar a Herança módulo 'calendar'
- Adiciona método 'can_send_email' para poder herdar em outros módulos e tratar o envio do e-mail do evento.
- Adiciona LOG do e-mail enviado.
- Atualiza tradução pt_br do módulo.
Dados da tarefa: [T8295](https://multi.multidados.tech/web?debug#id=8704&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
PR(s) relacionado(s) (se houver): [1418](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1418)
=> T8295 - Adicionar na Agenda o Status: RESERVADA

addons/web/static/src/js/views/form/form_controller.js
Adiciona function 'get_otherItems' p/facilitar herança módulo 'web'
Dados da tarefa: [T8297](https://multi.multidados.tech/web?debug#id=8706&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
PR(s) relacionado(s) (se houver): [1420](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1420)
=> T8297 - Adicionar funcionalidade de Criar Campos dinâmicos no BR_BASE

addons/calendar/models/calendar.py
* Corrige timezone da horas de inicio/fim dos .ics
Invites enviados via .ics estavam com a timezone UTC
Dados da tarefa: [T8341](https://multi.multidados.tech/web?debug#id=8750&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T8341 - Verificar a geração do arquivo .ics ao enviar os invites atraves do sistema

addons/hr_expense/views/hr_expense_views.xml, addons/purchase/views/product_views.xml, odoo/models.py
- Adiciona atributos nas views do Core
- Facilita necessidade de herança.
- Adiciona parâmetro 'kind' na função do efeito de notificar (effect_notify)
- Adiciona o parâmetro para facilitar a chamada da função, passando somente o param 'kind' e o ícone e título são automaticamente selecionados.
- [T8339](https://multi.multidados.tech/web?#id=8748&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [l10n_br](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1431)
- [private-addons](https://github.com/multidadosti-erp/multidadosti-private-addons/pull/913)
- [financial-addons](https://github.com/multidadosti-erp/multidadosti-financial-addons/pull/510)
- [channel-addons](https://github.com/multidadosti-erp/multichannels-addons/pull/85)
=> T8339 - Desenvolvimento da postagem de despesas para o Conta Corrente

addons/crm/data/crm_lead_demo.xml, addons/mail/data/mail_channel_demo.xml, addons/mail/data/mail_demo.xml, addons/mail/models/mail_message.py, addons/mail/models/mail_thread.py, addons/mail/models/res_partner.py, addons/mail/views/mail_message_views.xml, addons/mail/wizard/mail_compose_message.py, addons/mail/wizard/mail_compose_message_view.xml, addons/project/data/project_demo.xml, addons/sale/data/sale_demo.xml, addons/survey/wizard/survey_email_compose_message.py, addons/survey/wizard/survey_email_compose_message.xml, addons/test_mail/tests/test_mail_channel.py, addons/test_mail/tests/test_mail_gateway.py, addons/test_mail/tests/test_mail_message.py, addons/test_mail/tests/test_message_compose.py, addons/test_mail/tests/test_message_track.py, addons/web/static/src/scss/control_panel.scss, addons/website_mail_channel/controllers/main.py, addons/website_mail_channel/views/website_mail_channel_templates.xml
[Troca nome do campo 'parent_id' para 'message_parent_id' módulo 'mail'](https://github.com/multidadosti-erp/odoo/commit/2390f114a5fe2f7627deb83880b28e0d708f4007) 
- Estava dando conflito ao Cadastro Parceiros/Contatos ao enviar o
campo parent_id por contexto.
[Atualiza Teste módulo 'mail'](https://github.com/multidadosti-erp/odoo/commit/2dc4c33302292162245188a3c59af41ed049d1e2) 
Trocado nome do campo 'parent_id' para 'message_parent_id' módulo 'mail'
- Estava dando conflito ao Cadastro Parceiros/Contatos ao enviar o
campo parent_id por contexto.
[Troca campo 'parent_id' para 'message_parent_id' módulo 'website_mail_channel'](https://github.com/multidadosti-erp/odoo/commit/d84a7d9ff8f5122fae7c7f106cb09aa4ff79fc50) 
- Estava dando conflito ao Cadastro Parceiros/Contatos ao enviar o
campo …
=> T8390 - Erro ao cadastrar um contato diretamente pela tela do Orçamento

addons/account/models/account_invoice.py, addons/account/models/account_move.py, addons/account/views/account_view.xml
Ajusta Campo 'currency_id' módulo 'account'
Dados da tarefa: [T8412](https://multi.multidados.tech/web?debug#id=8821&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
PR(s) relacionado(s) (se houver): 
[919](https://github.com/multidadosti-erp/multidadosti-private-addons/pull/919)
[1458](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1458)
=> T8412 - Adicionar no Contrato de Serviço a Moeda para Faturamento

odoo/tools/config.py
* Adiciona chave de criptografia
Chave utilizada apenas em testes, ja que ambientes de produção possuem sua propria key
Dados da tarefa: [T8410](https://multi.multidados.tech/web#id=8819&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T8410 - Integrar novo sistema de cadastro de certificados na consulta do SEFAZ

addons/point_of_sale/static/src/js/models.js, addons/product/models/product_pricelist.py
[Ajusta Order Pesquisa Tabela Preço módulo 'point_of_sale'](https://github.com/multidadosti-erp/odoo/commit/4e4658991483576d7833a8a4c04f4cc6037620c8) 
- Odoo Não priorizava os produtos, gerando erro em tabelas de preço
com linhas globais.
[Ajusta Order Pesquisa Tabela Preço módulo 'product'](https://github.com/multidadosti-erp/odoo/commit/fd6f463a33693e362a89e0553a918754ddcbb789) 
- Odoo Não priorizava os produtos, gerando erro em tabelas de preço
com linhas globais.
Dados da tarefa: [T8463](https://multi.multidados.tech/web?&debug=#id=8872&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
PR(s) relacionado(s) (se houver): [1470](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1470)
=> T8463 - Produtos não estão atualizando o preço no POS de acordo com a lista de preços

odoo/modules/db.py, odoo/modules/registry.py
[Adiciona método 'create_unaccent' módulo 'modules'](https://github.com/multidadosti-erp/odoo/commit/8a650b6b8a0fb33d2a024f140e55b037200a253e) 
- Método para criar automaticamente a exstensão do postgree 'unaccent'
Dados da tarefa: [T8515](https://multi.multidados.tech/web?debug#id=8924&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T8515 - Alterar a busca (pesquisa) do sistema para que possibilite a busca por cadastros ignorando a acentuação utilizada no cadastro

odoo/models.py
- Correção no efeito de Notificação self.effect_notify(sticky=False)
- [T7734](https://multi.multidados.tech/web?#id=8143&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [l10n_br](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1472)
- [web-addons](https://github.com/multidadosti-erp/multidadosti-web-addons/pull/173)
=> T7734 - Melhorias no processo de ticket, diagnostico e orçamento para radio

addons/sale/i18n/pt_BR.po, addons/sale/views/sale_views.xml
- Alterações na view de kanban sale_order, melhorias para herança
- Adiciona tradução para o módulo de Vendas ('sale')
- [T8514](https://multi.multidados.tech/web?#id=8923&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [l10n_br](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1496)
- [private-addons](https://github.com/multidadosti-erp/multidadosti-private-addons/pull/941)
=> T8514 - Incluir na Tela de Kanbam do Orçamento os marcadores selecionados nesta proposta.

addons/sale/i18n/pt_BR.po, addons/sale/i18n/sale.pot
- Corrige tradução do módulo de Vendas
- Adiciona termos no arquivo .pot para funcionar corretamente.
- [T8595](https://multi.multidados.tech/web?#id=9004&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [l10n_br](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1504)
=> T8595 - Correção no kanban de vendas

addons/account/models/account_invoice.py
[Adiciona Valor sem Impostos as Parcelas módulo 'account'](https://github.com/multidadosti-erp/odoo/commit/b457f5321f1fd57346e5d073a347e43e27604c11) 
- Objetivo é ter o valor bruto, para cálculos gerais sem considerar
os impostos embutidos.
Dados da tarefa: [T8636](https://multi.multidados.tech/web#id=9045&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
[1535](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1535)
[949](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1535)
[329](https://github.com/multidadosti-erp/multidadosti-report-addons/pull/329)
=> T8636 - Gerar Contratos de Serviço de Eventos Fixos e Recorrentes com valores líquidos para o Fluxo de Caixa

addons/sale_stock/tests/test_sale_stock.py, addons/stock/models/stock_picking.py
Ajusta Separação do Estoque módulo 'stock'
- Adiciona verificação para não separar movimentos com o move_id null, pois em alguma situação específica o Odoo esta gerando tais movimentações gerando duplicidade e erro no sistema.
Dados da tarefa: [T8653](https://multi.multidados.tech/web#id=9062&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
PR(s) relacionado(s) (se houver): [1543](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1543)
=>  T8653 - Erro de Duplicidade de Produtos na Separação de Estoque

addons/account/models/account_invoice.py
Ajusta Geração Parcelas Pgto módulo 'account'
- Estava duplicando as datas refente a valor sem taxa de impostos.
Dados da tarefa: [T8670](https://multi.multidados.tech/web#id=9079&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T8670 - Verificar pedidos da kanxa que não estão integrando

addons/calendar/models/calendar.py
* Corrige envio de email quando atividades estao com email desabilitado
Sistema estava enviando email de agendamento de atividades mesmo quando a opção de envio estava desmarcada.
Foi adicionada um verificacao para o checkbox de envio da atividade, ja que o envio do email é realizado no meio do metodo, impossibilitando que o mesmo seja sobrescrito
Dados da tarefa: [T8669](https://multi.multidados.tech/web#id=9078&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T8669 - Sistema está enviado e-mail de alerta mesmo com a opção desmarcada

addons/web/static/src/js/fields/relational_fields.js
- Corrige a falta de efeito da opção 'no_create_edit' em campos M2O
- A option 'no_create_edit' não estava fazendo efeito em campos many2one nas views.
- [T8722](https://multi.multidados.tech/web?#id=9131&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T8722 - Retirar a opção de criar item ao vincular um fornecedor

addons/web/static/src/js/views/kanban/kanban_column.js, addons/web/static/src/js/views/kanban/kanban_record.js, addons/web/static/src/js/views/kanban/kanban_renderer.js
- Adiciona funcionamento de atributos de campos readonly no kanban
- Corrige no agrupamento de registros, o bloqueio caso o campo tenha nos attrs declarados, uma regra para o readonly.
- Quando carregamos um campo no kanban, verifica o atributo `attrs` dos campos para determinar se pode ser arrastado o registro para outras colunas do kanban, alterando o valor do campo de agrupamento.
- Adiciona verificação da tag 'dragging' nas options dos campos no kanban, para forçar que um registro possa ter o valor alterado quando agrupado, apesar de estar bloqueado na tag `kanban`.
- [T8719](https://multi.multidados.tech/web?#id=9128&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [oca-web](https://github.com/multidadosti-erp/web/pull/14)
- …
=> T8719 - Adicionar no Kanban dos Orçamentos as Categorias dos Produtosseta

addons/sale/views/sale_views.xml, addons/sale_margin/views/sale_margin_view.xml, addons/sale_stock/views/sale_order_views.xml, addons/stock_dropshipping/tests/__init__.py, addons/stock_dropshipping/views/sale_order_views.xml, odoo/modules/loading.py
[Comenta XML substituido no br_sale módulo 'sale'](https://github.com/multidadosti-erp/odoo/commit/a87d4cd17f3d619b59142c44d102c03b08ad8b9b)
[Comenta XML substituido no br_sale módulo 'sale_margin'](https://github.com/multidadosti-erp/odoo/commit/45da0eecf904eaa6fe556a62cf835f4b7f9d9ca7)
[Comenta XML substituido no br_sale módulo 'sale_stock'](https://github.com/multidadosti-erp/odoo/commit/5fd6b1d37ed13c5c71f94f6f86c1f258c2694f12)
Dados da tarefa: [T8743](https://multi.multidados.tech/web?debug=#id=9152&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
[1590](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1590)
[963](https://github.com/multidadosti-erp/multidadosti-private-addons/pull/963)
=> T8743 - Criar acesso as Linhas do Orçamento via Menu e Botão no Form

addons/web/static/src/js/fields/relational_fields.js, addons/web/static/src/js/views/form/form_controller.js, odoo/import_xml.rng, odoo/tools/convert.py
- Implementa utilização de KWARGS em tags <function> no XML
- Ao cirar uma função para ser executada na atualização do módulo, com a tag `<function>` no xml, somente era possível passar os argumentos nas tags `<value>` da forma sequencial de 'args'.
- Adiciona atributo `name` no rng da tag value, para que o valor do argumento passado seja executado como kwarg, sendo o valor do name a chave do kwarg.
- Definição de arg e kwarg:
- *arg*: argumento passado para função posicionalmente.
- *kwarg*: argumento passdo para a função nominalmente (key-arg)
- Permite a exclusão de itens na hora de selecionar valor Selection
- Permite remover opções de seleção no campo Selection.
- Adicionar na view a option no campo selection `restrict_selection`
- Adiciona JS para tratar cliques em botões dropdown …
=> T8807 - Melhorias no core

odoo/addons/base/models/res_currency.py, odoo/addons/base/models/res_lang.py
- Formatação de moeda específica quando chamada a partir de uma moeda
- A função `get_locale_value` é adicionada nas models padrão, para obter um valor no formato monetário para a localização atual, com base na linguagem do usuário ativo.
- A função foi sobrescrita para ser executada diferente quando chamada a partir de uma moeda (res.currency)
- Na obtenção da linguagem, adiciona obtenção de linguagens inativas quando especificadas o campo `code` da linguagem.
- [T8827](https://multi.multidados.tech/web?debug#id=9236&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [private-addons (anterior)](https://github.com/multidadosti-erp/multidadosti-private-addons/pull/972)
- [private-addons (novo)](https://github.com/multidadosti-erp/multidadosti-private- …
=> T8827 - Ajustes Contrato Tipo Hora

addons/hr/views/hr_views.xml, addons/hr_contract/security/security.xml, addons/hr_holidays/views/hr_views.xml, addons/hr_recruitment/views/hr_recruitment_views.xml, addons/sale_timesheet/tests/common.py, addons/sale_timesheet/tests/test_project_billing.py, odoo/addons/base/views/res_users_views.xml
- Bloqueio da criação de 'hr.employee' a partir das Actions da model
- Os colaboradores, agora são criados somente pelo wizard adicionado no 'br_hr' (`partner.to.employee.wizard`)
- Corrige atualização de grupos de regras ref. à contratos de RH
- As alterações feitas anteriormente para os grupos e regras de registro ref a contratos de RH (`hr_contract`) não estavam tendo efeito por conta do campo `noupdate=True`.
- Adiciona function no XML para alterar os valores desse campo dos registros dos groups e regras de contrato de rh.
- [T8805](https://multi.multidados.tech/web?#id=9214&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [l10n_br](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1614)
- …
=> T8805 - Ajustar estrutura de dados dos Colaboradores

odoo/addons/base/views/ir_model_views.xml
Adiciona class="oe_button_box" Form Campos módulo 'base'
- Class adicionada para facilitar a adição de botões nos módulos que herdam essa view.
Dados da tarefa: [T8870](https://multi.multidados.tech/web?debug=1#id=9279&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
PR(s) relacionado(s) (se houver): [1624](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1624)
=> T8870 - Tornar Obrigatório o preenchimento dos campos "midia e campanha" - Módulo de Oportunidades/Prospectos.

addons/sale/models/sale.py
Ajusta método 'onchange_partner_id' módulo 'sale'
- Adiciona verificação para não regravar campos caso não tenha mudado o partner_id do pedido.
Dados da tarefa: [T8874](https://multi.multidados.tech/web?debug=1#id=9283&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
PR(s) relacionado(s) (se houver): [1625](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1625)
=> T8874 - Erro ao Editar o Orçamento

addons/account/models/account_invoice.py, addons/product/data/product_data.xml, addons/product/models/product.py, addons/product/models/product_template.py, addons/purchase/models/purchase.py, addons/stock_account/tests/test_stockvaluation.py
[Adiciona Nova Precision 'Purchase Price' módulo 'product'](https://github.com/multidadosti-erp/odoo/commit/0978ef9751b524af89829ba4fcadf809e1f634a0) 
- Para ser utilizado nos valores de compras.
[Ajusta Precision para Compras módulo 'purchase'](https://github.com/multidadosti-erp/odoo/commit/a890f129fc6bab9d1c8bc67d428299a25bc11a08)
Dados da tarefa: [T8872](https://multi.multidados.tech/web?debug=1#id=9281&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
PR(s) relacionado(s) (se houver): [1627](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1627)
=> T8872 - Erro importação XML - Qtd casas decimais

addons/product/models/product_pricelist.py, addons/sale/models/sale.py, addons/sale/tests/test_onchange.py, addons/sale_stock/i18n/pt_BR.po, addons/web/static/src/js/core/domain.js, addons/web/static/src/js/fields/basic_fields.js, addons/web/static/src/js/fields/relational_fields.js, addons/web/static/src/scss/form_view.scss
[Ajusta Métodos de Retorno Preço módulo 'product'](https://github.com/multidadosti-erp/odoo/commit/09c4edbb02e18bb4c921cc0e04d0496fe90a8c93)
[Ajusta Métodos ref aos Valores módulo 'sale'](https://github.com/multidadosti-erp/odoo/commit/c6eb646d575db24726728c254c5de2fcc4a948ce)
[Ajusta tradução pt_br do módulo 'sale_stock'](https://github.com/multidadosti-erp/odoo/commit/76e5e5498c32491749ab5aacbccb57bad3084a04)
[Ajusta CSS 'Notebooks' módulo 'web'](https://github.com/multidadosti-erp/odoo/commit/d1829d5d64506db8cf8d1e51e6461edf25c80edf) 
- Diminui a margem superior para diminuir os espaços em branco.
[Ajusta JS 'domain' módulo 'web'](https://github.com/multidadosti-erp/odoo/commit/1507360a3101df4989135284a42dd07d7d986793) 
- Adiciona verificação do campo com '.parent' para evitar erros no …
=> T8891 - Remover Campo Preço Unitário Base do Comercial e utilizar o padrão do Odoo

addons/crm/i18n/pt_BR.po, addons/link_tracker/i18n/pt_BR.po, addons/utm/i18n/pt_BR.po, addons/website_sale_link_tracker/i18n/pt_BR.po
Corrige tradução de "Medium" para "Média" nos módulos 'crm', 'link_tracker', 'utm' e 'website_sale_link_tracker'
Dados da tarefa: [T8911](https://multi.multidados.tech/web#id=9320&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
* https://github.com/multidadosti-erp/multichannels-addons/pull/108
* https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1641
=> T8911 - Erros de tradução

addons/web/static/src/js/views/calendar/calendar_model.js
* Remove opção de visualizar todos os calendarios
Objetivo é melhorar a privacidade do usuario, permitindo que somente ele veja seu eventos de calendario.
Dados da tarefa: [T8839](https://multi.multidados.tech/web#id=9248&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T8839 - Corrigir Visão do Calendario com base na permissão do usuario

addons/mrp/i18n/pt_BR.po, addons/purchase/i18n/pt_BR.po, addons/sale/i18n/pt_BR.po, addons/sale/i18n/sale.pot, addons/sale/views/sale_views.xml, addons/stock/i18n/pt_BR.po
[Ajusta Tradução pt_br do módulo 'stock'](https://github.com/multidadosti-erp/odoo/commit/69f91dc9e54790c3e5fa8f3da366467f78aedf43)
[Ajusta Menu Pedidos e Traduções no Core do Odoo](https://github.com/multidadosti-erp/odoo/commit/ff55d7499379a3a3f387d63ed4be746ca812d336) 
- Tradução pt_br para os módulos: 'mrp', 'purchase' e 'sale'
- Ajuste do Menu no módulo 'sale'
Dados da tarefa: [T8950](link)
=> T8950 - Ajustar menu Pedido nos Orçamentos e Traduções

addons/account/i18n/account.pot, addons/account/i18n/pt_BR.po, addons/account/views/account_journal_dashboard_view.xml, addons/account/views/account_payment_view.xml
Adiciona Confirmação Action módulo 'account'
- Confirmação adicionada na action 'set to Draft'.
- Sempre mostra o last_balance no Painel Financeiro.
- atualiza tradução do módulo.
Dados da tarefa: [T8941](https://multi.multidados.tech/web?debug#id=9350&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
PR(s) relacionado(s) (se houver): [1650](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1650)
=> T8941 - Títulos Cancelados - Está permitindo Alterar Data e Valor

odoo/models.py
Adiciona sudo() translation read 'models.py' do core.
- Adicionado sudo para evitar erros de permissão do Odoo para atualizar campos Related tem tabelas que o usuário não tem acesso.
Dados da tarefa: [T8959](https://multi.multidados.tech/web?debug#id=9368&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T8959 - Erro ao trocar nome de produto ja cadastrado, o sistema está apresentando restrição de acesso.

addons/hr/i18n/pt_BR.po, addons/hr/models/__init__.py, addons/hr/models/hr.py, addons/hr/models/hr_job_mixin.py, addons/hr_contract/i18n/pt_BR.po, addons/hr_contract/models/__init__.py, addons/hr_contract/models/hr_contract.py, addons/hr_contract/models/hr_contract_mixin.py, addons/hr_contract/views/hr_contract_views.xml, addons/hr_expense/i18n/pt_BR.po, addons/hr_expense/views/hr_expense_views.xml, addons/hr_payroll/models/hr_contract.py, addons/hr_payroll/views/hr_contract_views.xml, addons/website_sale/controllers/main.py
- Altera estrutura inicial do form da model 'hr_contract'
- Ajusta estrutura básica para não ter que alterar totalmente ela via Xpaths.
- "hr.contract.mixin" para campos básicos relacionado ao contrato HR
- Para evitar a criação do mesmo campo em algumas tabelas, foi adicionado o mixin para garantir que mantenha os campos sempre herdados.
- Importa alguns campos que eram exclusivos do 'hr.payroll' para o 'hr_contract'
- Herdado também no módulo "br_hr_contract"
- "hr.job.mixin" para campos básicos relacionado ao emprego
- Para evitar a criação do mesmo campo em algumas tabelas, foi adicionado o mixin para garantir que mantenha os campos sempre herdados.
- Utilizado nos commits seguintes no mixin 'hr.contract'.
- [T8801](https://multi.multidados.tech/web?#id=9210&action=323&active_id=61&mod …
=> T8801 - Implementar contratos de RH para colaboradores (Pgto)

addons/mail/models/mail_activity.py
- Separação de código para herança em oca/social
- A função de obtenção de atividades pela View do tipo 'activity', realiza um read_group, o qual ignora o método search de atividades ativas.
- Adiciona uma função para obter o domain, aonde é herdada no módulo `oca/social/mail_activity_done` para utilização do active=True e done=False.
- [T8957](https://multi.multidados.tech/web?#id=9366&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [oca/social](https://github.com/multidadosti-erp/social/pull/28)
=> T8957 - Data errada de aviso de Atividade

addons/crm/wizard/crm_partner_binding.py
* Remove opção de criar oportunidade sem parceiro
Remover a opção 'Não associe a um cliente' ao criar Oportunidade a partir do Prospecto
Dados da tarefa: [T9005](https://multi.multidados.tech/web#id=9414&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T9005 - Remover campo "Não associe a um cliente", ao realizar a conversão de prospecto para oportunidade.

addons/web/static/lib/fullcalendar/js/fullcalendar.js
- Lib 'fullcalendar.js': readonly do campo 'is_calendar_fixed'
- Adiciona verificação para deixar eventos do calendário como readonly quando o campo 'is_calendar_fixed' for = True.
- A alteração foi feita de forma que se o campo não exista, ele não muda o comportamento atual. Isso porque o campo é adicionado no módulo `br_calendar`.
- [T8990](https://multi.multidados.tech/web?#id=9399&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [l10n_br](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1667)
=> T8990 - Ao Criar uma Folga, espelhar no Calendário

addons/account/models/chart_template.py
Remove exclusao de pos. fiscal que estava causando conflito nos testes
Modulo não e usado em producao
- [T9002](https://multi.multidados.tech/web?debug=1#id=9411&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T9002 - Permitir cancelar separação de orçamento de locação sem contrato vinculado 

addons/web/i18n/pt_BR.po, addons/web/static/src/xml/base.xml, odoo/models.py
- Atualiza tradução do módulo WEB
- Adiciona botão para incluir actions de exportação
- O botão foi adicionado no core, mas só é renderizado caso caso modulos adicionem actions com binding_type in `['export', 'export_action']`.
- Adiciona função para a obtenção das binding actions nas views
- O código foi transferido para uma função, para possibilitar a herança.
- A adaptação foi feita para a adição das actions de exportação:
- `binding_type = 'export'` ou `binding_type = 'export_action'`
- A nova inclusão foi feita no módulo `br_base_export_excel`.
- [T9064](https://multi.multidados.tech/web?#id=9473&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [l10n_br](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1705)
- …
=> T9064 - Adicionar no Botões de Exportar XLS as Ações do módulo br_base_export_xls

addons/web/static/src/js/core/domain.js
- Corrige filtros predefinidos de campos de data no domain
- Na 'search_view', os filtros de campos de data possuem valores padrões para os períodos ('Ultimos 30 dias', 'Ultimos 365 dias', 'Ontem', 'Hoje', ...), e os filtros de datas passadas estavam incorretos, passando 00:00 como hora ao inves de 23:59 para pegar o dia todo.
- Ajusta o filtro de "Ontem", aplicando a data correta para o relativedelta.
- [T9074](https://multi.multidados.tech/web?#id=9483&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [l10n_br](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1707)
=> T9074 - Ajuste Filtro (Oportunidades) e Add Filtro (Atividades)

addons/account/views/partner_view.xml, addons/calendar/models/calendar.py, addons/crm/models/res_partner.py, addons/web/static/src/js/views/calendar/calendar_model.js, addons/web/static/src/js/views/calendar/calendar_view.js, odoo/addons/base/views/res_partner_views.xml
- Obter as reuniões do parceiro sem misturar com outros eventos
- Foi adicionado uma função para obtenção das reuniões do parceiro, para quando adicionado a criação de `calendar.event` em outras models, não misturar com as Reuniões
- Correções na criação do calendar.event
- O campo res_model_id sem valor, faz com que rotinas sejam chamadas desnecessáriamente.
- If causava erro quando o evento tinha o valor do stop, atualizado, e o start não.
- Alterações no JavaScript da view de Calendários (filtros padrão)
- **`calendar_view.js`**:
- Inclui carregamento de registros utilizados como filtro padrão da view de calendários.
- Cria estrutura do record para ser enviado para o CalendarModel.
- **`calendar_model.js`**:
- Leitura dos registros carregados pelas views e composição para a …
=> T9041 - Criar Consultas e Testes pelo Cadastro do Cliente (Paciente)

addons/web/static/src/js/fields/relational_fields.js
- Adapta 'deletable' de campos X2Many, para exclusão dinâmica
- A exclusão dinâmica adicionada no `br_base`, faz com que remova o ícone de exclusão do FormDialog, de campos X2Many.
- Porém o form dialog ainda aparece o botão de "Remover".
- [T8967](https://multi.multidados.tech/web?#id=9376&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [l10n_br](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1724)
- [l10n_br (antigo)](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1714)
=> T8967 - o sistema não pode permitir alterações de itens da fatura quando a separação já estiver sido validada.

addons/product/models/product_pricelist.py, addons/sale/models/sale.py
Ajusta método 'def product_uom_change' módulo 'sale'
- Fixa o parametro 'uom_qty_change' em um novo método como False.
- Ajusta Verificação para Obter o old_price.
Dados da tarefa: [T9151](https://multi.multidados.tech/web#id=9560&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
PR(s) relacionado(s) (se houver): [1726](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1726)
=> T9151 - Erro ao tentar incluir itens no orçamento

addons/point_of_sale/views/pos_order_view.xml
Adiciona classe 'oe_highlight' ao botão de faturar POS
Adiciona classe 'oe_highlight' ao botão de faturas no formulário de pedidos do ponto de venda
Dados da tarefa: [T9167](https://multi.multidados.tech/web#id=9576&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T9167 - Corrigir aliquota dos impostos ICMS, PIS e Cofins em faturas do POS

addons/product/i18n/pt_BR.po, addons/product/models/product_pricelist.py, addons/product/views/product_pricelist_views.xml, addons/sale/models/sale.py
- Atualiza tradução do módulo 'Product'
- Permite a inclusão de um domain em formato de string para campos
- Na criação de campos relacionais, a utilização do domain, não permitia que strings fossem passadas como domain.
- Permite strings, para deixar o desenvolvimento mais dinâmico e prático.
- Adiciona itens de parceiros nas listas de preços
- Adiciona campos para filtrar os registros e facilitar na visualização do xml.
- Adiciona campo para determinar que o form está sendo aberto para um item de parceiro.
- Ajusta acesso à valores de objetos (variável pricelist)
- Insere os itens da tabela de preços em um Notebook
- Adapta Query para obtenção dos itens das listas de Peços
- Adapta para obter prioritariamente itens da lista que sejam do parceiro vinculado ao orçamento.
- Adiciona campo …
=> T9139 - Criar Tabela de Preço por Item relacionado ao Cliente

addons/sale_crm/i18n/pt_BR.po, addons/sale_crm/i18n/sale_crm.pot, addons/sale_crm/models/crm_lead.py
Adiciona novo Campos módulo 'sale_crm'
- Adiciona Campos Relacionados aos Orçamentos, antes utilizados no br_sale_crm, para otimizar os cálculos e não duplicar as rotinas de onchange.
- Atualiza tradução pt_br do módulo.
Dados da tarefa: [T9177](https://multi.multidados.tech/web#id=9586&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
PR(s) relacionado(s) (se houver): [1741](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1741)
=>  T9177 - Ao Aprovar uma Oportunidade o Valor esta sendo Zerado

odoo/models.py
- Corrige erro ao acessar valores em cache de registros apagados
- [T9133](https://multi.multidados.tech/web?#id=9542&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T9133 - Permitir cancelar evento que ja foi faturado para que o evento/contrato seja concluido

addons/web/static/src/xml/menu.xml, odoo/tools/convert.py
Adiciona web_icon aos sub-menus módulo 'web'
- Adicionado a tag 'web_icon' no '<menuitem>' para mostrar imagens do FontAwesome.
Ex: 
<menuitem id="service_contract_revenue" 
name="Revenue Contracts" 
groups="service_contract_management.group_contract_management" 
parent="service_contract_menu" 
action="service_contract_action_revenue"
===>              web_icon="fa fa-line-chart"
sequence="0"/>
Dados da tarefa: [T9231](https://multi.multidados.tech/web?debug=1#id=9640&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T9231 - Adicionar aos Menus e SubMenus do Sistema opção de web_icon

addons/web/static/lib/bootstrap/scss/_variables.scss, addons/web/static/src/scss/bootstrap_overridden.scss, addons/web/static/src/scss/form_view.scss
- Altera cor padrão para o estilo "text-muted"
- Altera cor para mais escuro, melhorando a visibilidade.
- [T9211](https://multi.multidados.tech/web?#id=9620&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T9211 - Ajusta a Cor dos Itens Separados no Stock Picking

addons/mail/static/src/xml/discuss.xml, odoo/__init__.py, odoo/fields.py
- Ajustes na renderização do ícone do canal de comunicação
- Importa a classe Command do Odoo 18 (x2many operations)
- No Odoo 18, é utilizado a classe Command para obter os valores de gravação para campos x2many.
- Ex: `[(4, <id>), (6, 0, [<ids>])]`
- [T9175](https://multi.multidados.tech/web?#id=9584&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [channel-addons](https://github.com/multidadosti-erp/multichannels-addons/pull/120)
=> T9175 - Adicionar Módulo EvoOdoo (adaptar da V18 para V12)

addons/web/static/src/js/chrome/action_manager.js, addons/web/static/src/js/core/dialog.js, addons/web/static/src/js/views/basic/basic_controller.js, addons/web/static/src/js/views/basic/basic_view.js
- Formata atributo options do Botão XML
- O atributo não formatava de dict Python para objeto JSON.
- Adapta ActionManager e basicController para enviar contexto ao Dialog
- Como o objeto ActionManager não possui o atributo context, deve passar forçadamente como `options`
- Formata atributo context da tag de botão no XML.
- Adapta "web.Dialog.js" para obter o contexto a partir das options
- O contexto do Dialog era obtido somente a partir do parent, na classe básica do `Widget.js`.
- Caso não tenha obtido no parent, como no caso do ActionManager, ao executar actions a partir de botões ou objetos de retorno em dicionários python, ele tenta a partir das options.
- [T9278](https://multi.multidados.tech/web?#id=9687&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
PRs …
=> T9278 - Habilitar a visualização expandida em Dialog Forms

addons/stock/models/stock_production_lot.py
Adiciona a definição de ordenação de serie/lot na tree
Dados da tarefa: [T9306](https://multi.multidados.tech/web#id=9715&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T9306 - Relatório de estoque atual não ordena por nro de série

addons/account/models/account_invoice.py
Ajusta método 'invoice_validate' módulo 'account'
- Verifica se o move_id existe para atribuir a 'ref'
Dados da tarefa: [T9322](https://multi.multidados.tech/web?debug#id=9731&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
[1812](https://github.com/multidadosti-erp/odoo-brasil-addons/pull/1812)
[536](https://github.com/multidadosti-erp/multidadosti-financial-addons/pull/536)
=> T9322 - Corrigir mensagem ao cancelar fatura com titulo cancelado

addons/web_tour/static/src/js/tip.js
Ajusta método 'destroy' Tip módulo 'web_tour'
- Adiciona verificação antes de remover a class para evitar erro de JS Uncaught TypeError: Cannot read properties of undefined (reading '0')
Dados da tarefa: [T9382](https://multi.multidados.tech/web?debug#id=9791&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T9382 - Erro JavaScript

addons/mail/models/mail_thread.py
- Ajusta função de obtenção do seguidor do registro
- A função percorria todos os campos para obter somente o campo `user_id`.
- [T9356](https://multi.multidados.tech/web?#id=9765&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
- [private-addons](https://github.com/multidadosti-erp/multidadosti-private-addons/pull/1068)
=> T9356 - Ao faturar eventos de contrato o sistema está atribuindo o usuário como seguindo e disparando e-mails

addons/sale_timesheet/security/sale_timesheet_security.xml
- Ajusta regra para visualização de linhas de orçamento (projeto)
- O campo project_id foi removido das linhas do pedido, mas ainda estava sendo utilizado para regra de registro.
- Torna ela atualizável e muda seu domain, removendo o campo antigo
- [T9435](https://multi.multidados.tech/web?debug#id=9844&action=323&active_id=61&model=project.task&view_type=form&menu_id=223)
=> T9435 - Erro ao tentar incluir um novo orçamento
